### ISSUE TITLE
Mps(0.2.8) and youtube blocked videos : Crash 

### ISSUE THREAD

**Issue by pam547** [mps-youtube/mps-youtube#1018]
Hi, thanks all for the result 
If the youtube video is blocked for any reasons mps-youtube crash with youtube-dl error messages.
The logs :

`ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.
ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.
ERROR: This video contains content from UMG, who has blocked it on copyright grounds.
Sorry about that.
ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.
ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.
Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2146, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2146, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2146, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/user1/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/home/user1/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video contains content from SME, who has blocked it in your country on copyright grounds.
Sorry about that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/bin/mpsyt", line 10, in <module>
    sys.exit(main.main())
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/main.py", line 148, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/main.py", line 65, in matchfunction
    func(*matches)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/commands/play.py", line 119, in play_all
    play(options, "1-" + str(len(g.model)))
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/commands/play.py", line 100, in play
    play_range(songlist, shuffle, repeat, override)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 49, in play_range
    video, stream = stream_details(song, override=override, softrepeat=softrepeat)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 171, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 171, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 171, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/home/user1/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 186, in stream_details
    cached = g.streams[song.ytid]
KeyError: 'OQM5-Ks64is'
`

## Issue / Suggestion

With python we could use try : except:

## Your Environment
I use mps-youtube often with :
//
pull
shuffle
* 

~$ .local/bin/mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.09.12.1
Python version     : 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.9.0-11-amd64-x86_64-with-debian-10.1
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/user1/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : fr_FR.UTF-8

Debian Buster XFCE

mpv

**Comment by Nojus297** [comment]
Could you give an example link of such blocked video?

**Comment by selplacei** [comment]
https://www.youtube.com/watch?v=B4dIAUqmHkw&list=PLGJtoO98wpAJQ0otvhzvjCmIsvoC48o_9&index=67

The funny thing is, it even breaks YouTube itself if it's in a playlist.
