### ISSUE TITLE
crash at startup: 'pafy!=0.4.0,!=0.4.1,!=0.4.2,>=0.3.82' distribution was not found

### ISSUE THREAD

**Issue by edricus** [mps-youtube/mps-youtube#1033]
## Issue
Crash at startup : 
```
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pafy!=0.4.0,!=0.4.1,!=0.4.2,>=0.3.82' distribution was not found and is required by mps-youtube


```
## Your Environment
Archlinux 5.3.12-arch1-1
mps-youtube 0.2.8-3

**Comment by edricus** [comment]
fixed installing python-pafy-0.5.4-5 instead of python-pafy-git 0.5.4.r16.g7c31503-1
