### ISSUE TITLE
Error when playing video, AUR development branch

### ISSUE THREAD

**Issue by Savanta** [mps-youtube/mps-youtube#1122]
<code>Exception in thread Thread-2:                                                                                                                                                                  
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/mps_youtube/mpris.py", line 227, in bindmpv
    self.setproperty(resp['name'], resp['data'])
KeyError: 'data'
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 33, in <module>
    sys.exit(load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')())
  File "/usr/lib/python3.8/site-packages/mps_youtube/main.py", line 153, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.8/site-packages/mps_youtube/main.py", line 70, in matchfunction
    func(*matches)
  File "/usr/lib/python3.8/site-packages/mps_youtube/commands/play.py", line 102, in play
    g.PLAYER_OBJ.play(songlist, shuffle, repeat, override)
  File "/usr/lib/python3.8/site-packages/mps_youtube/player.py", line 79, in play
    self._playsong()
  File "/usr/lib/python3.8/site-packages/mps_youtube/player.py", line 138, in _playsong
    self._launch_player()
  File "/usr/lib/python3.8/site-packages/mps_youtube/player.py", line 298, in _launch_player
    self.launch_player(cmd)
  File "/usr/lib/python3.8/site-packages/mps_youtube/players/mpv.py", line 135, in launch_player
    self._player_status(self.songdata + "; ", self.song.length)
  File "/usr/lib/python3.8/site-packages/mps_youtube/players/mpv.py", line 188, in _player_status
    if resp['data'] is not None:
KeyError: 'data'</code>

**Comment by migueldeoleiros** [comment]
Getting the same or simmilar issue on Void linux using the development python3 package 

`Exception in thread Thread-2:0 Mb
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/miguel/.local/lib/python3.9/site-packages/mps_youtube/mpris.py", line 227, in bindmpv
    self.setproperty(resp['name'], resp['data'])
KeyError: 'data'
Traceback (most recent call last):
  File "/home/miguel/.local/bin/mpsyt", line 8, in <module>
    sys.exit(main.main())
  File "/home/miguel/.local/lib/python3.9/site-packages/mps_youtube/main.py", line 153, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/miguel/.local/lib/python3.9/site-packages/mps_youtube/main.py", line 70, in matchfunction
    func(*matches)
  File "/home/miguel/.local/lib/python3.9/site-packages/mps_youtube/commands/play.py", line 102, in play
    g.PLAYER_OBJ.play(songlist, shuffle, repeat, override)
  File "/home/miguel/.local/lib/python3.9/site-packages/mps_youtube/player.py", line 79, in play
    self._playsong()
  File "/home/miguel/.local/lib/python3.9/site-packages/mps_youtube/player.py", line 138, in _playsong
    self._launch_player()
  File "/home/miguel/.local/lib/python3.9/site-packages/mps_youtube/player.py", line 298, in _launch_player
    self.launch_player(cmd)
  File "/home/miguel/.local/lib/python3.9/site-packages/mps_youtube/players/mpv.py", line 135, in launch_player
    self._player_status(self.songdata + "; ", self.song.length)
  File "/home/miguel/.local/lib/python3.9/site-packages/mps_youtube/players/mpv.py", line 188, in _player_status
    if resp['data'] is not None:
KeyError: 'data'`

**Comment by migueldeoleiros** [comment]
It's seems to be an issue with mpv 0.32.0_4 if I change the player to vlc it works as intended. 
use `set player vlc`

**Comment by chrisdginn** [comment]
Having this issue as well.  Works with VLC but not with mpv.  mpv version is 0.33.0.  mpsyt version is 0.2.8

**Comment by migueldeoleiros** [comment]
I fixed it by installing mplayer. which does not start a window like vlc.

**Comment by Masacaai** [comment]
This is a duplicate of [this issue](https://github.com/mps-youtube/mps-youtube/issues/1134).
Apply the changes mentioned in that commit and it should start working as intended.
