### ISSUE TITLE
Crash (sometimes) when looking for videos by user

### ISSUE THREAD

**Issue by henkmet** [mps-youtube/mps-youtube#1125]
I use `url https://youtube.com/watch?v=OriOY2EnaF8` to get a list with one video. Upon doing `u 1` to see other videos by the same user, the program crashes (mps-youtube-git on arch from aur, same behaviour after fresh build).

The error message(s) is/are:
```
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 33, in <module>
    sys.exit(load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')())
  File "/usr/lib/python3.8/site-packages/mps_youtube/main.py", line 153, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.8/site-packages/mps_youtube/main.py", line 70, in matchfunction
    func(*matches)
  File "/usr/lib/python3.8/site-packages/mps_youtube/commands/search.py", line 567, in user_more
    user, channel_id = channelfromname(paf.author)
  File "/usr/lib/python3.8/site-packages/mps_youtube/commands/search.py", line 141, in channelfromname
    userinfo = pafy.call_gdata('channels', qs)['items']
KeyError: 'items'
```

**Comment by elig0n** [comment]
The problem is in pafy/Youtube

**Comment by henkmet** [comment]
If there's a problem in pafy/youtube, I would expect mps-youtube to handle that more gracefully than crashing to terminal.

**Comment by iamtalhaasghar** [comment]
no more an issue in yewtube `v 2.10.2`
