### ISSUE TITLE
403 error 

### ISSUE THREAD

**Issue by arpyo** [mps-youtube/mps-youtube#1150]
I can't start mpsyt 0.2.8.  This is on AntiX Linux (a Debian).  I get the following error, which concludes with 403.
Welcome pointers.  Thank you!  

File "/usr/lib/python3/dist-packages/pafy/util.py", line 27, in call_gdata
    data = g.opener.open(url).read().decode('utf-8')
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/usr/lib/python3/dist-packages/mps_youtube/init.py", line 59, in init
    cache.load()
  File "/usr/lib/python3/dist-packages/mps_youtube/cache.py", line 34, in load
    pafy.load_cache(cached['pafy'])
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 182, in load_cache
    set_categories(newcache.get('categories', {}))
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 169, in set_categories
    catinfo = call_gdata('videoCategories', query)
  File "/usr/lib/python3/dist-packages/pafy/util.py", line 35, in call_gdata
    raise GdataError(errmsg)
pafy.util.GdataError: Youtube Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.

**Comment by arpyo** [comment]
I removed the app, deleted the folder containing the cache and config, and reinstalled.  Then I set my own API key.  Up and running!
