### ISSUE TITLE
Exception in thread Thread-2

### ISSUE THREAD

**Issue by senran101604** [mps-youtube/mps-youtube#1165]
It gives me this error after searching

`> Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "mps_youtube\streams.py", line 180, in _preload
  File "mps_youtube\streams.py", line 51, in get
  File "mps_youtube\util.py", line 205, in get_pafy
  File "site-packages\pafy\pafy.py", line 124, in new
  File "site-packages\pafy\backend_youtube_dl.py", line 29, in __init__
  File "site-packages\pafy\backend_shared.py", line 96, in __init__
  File "site-packages\pafy\backend_youtube_dl.py", line 38, in _fetch_basic
  File "site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "site-packages\youtube_dl\extractor\common.py", line 500, in extract
  File "site-packages\youtube_dl\extractor\youtube.py", line 1613, in _real_extract
TypeError: argument of type 'NoneType' is not iterable
`

I'm using Windows 10 x86-64 bit
and downloaded mps-youtube's binary in the [Releases](https://github.com/mps-youtube/mps-youtube/releases) as mentioned in the Readme.md

**Hope you'll help me**  😃

**Comment by senran101604** [comment]
I'd now just downloaded it using pip and it works well :D

**Comment by valkyrienyanko** [comment]
I am also on win 10 64bit and downloaded latest version from releases and getting a similar error.

```
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "mps_youtube\streams.py", line 180, in _preload
  File "mps_youtube\streams.py", line 51, in get
  File "mps_youtube\util.py", line 205, in get_pafy
  File "site-packages\pafy\pafy.py", line 124, in new
  File "site-packages\pafy\backend_youtube_dl.py", line 29, in __init__
  File "site-packages\pafy\backend_shared.py", line 96, in __init__
  File "site-packages\pafy\backend_youtube_dl.py", line 38, in _fetch_basic
  File "site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "site-packages\youtube_dl\extractor\common.py", line 500, in extract
  File "site-packages\youtube_dl\extractor\youtube.py", line 1613, in _real_extract
TypeError: argument of type 'NoneType' is not iterable
```

I'm sure I could get it working if I installed python and installed through pip but I just don't want to go through the hassle, cool project though!
