### ISSUE TITLE
No video at all

### ISSUE THREAD

**Issue by EnigmaticJihad** [mps-youtube/mps-youtube#1184]
Hello, I'm using Arch Linux and `mps-youtube-git` from AUR. Bellow is the details from `mpsyt --version`

```
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2021.12.17
Python version     : 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
Processor          :
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.15.12-zen1-1-zen-x86_64-with-glibc2.33
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/zed/.config/mps-youtube
env:TERM           : st-256color
env:SHELL          : /bin/zsh
env:LANG           : en_US.UTF-8
```

I can't see any video. I've tried `mpv`, which gives me the following error. 

```
Exception in thread Thread-2 (bindmpv):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/mps_youtube/mpris.py", line 227, in bindmpv
    self.setproperty(resp['name'], resp['data'])
KeyError: 'data'
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 33, in <module>
    sys.exit(load_entry_point('mps-youtube==0.2.8', 'console_scripts',
'mpsyt')())
  File "/usr/lib/python3.10/site-packages/mps_youtube/main.py", line 153, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.10/site-packages/mps_youtube/main.py", line 70, in matchfunction
    func(*matches)
  File "/usr/lib/python3.10/site-packages/mps_youtube/commands/play.py", line 102, in play
    g.PLAYER_OBJ.play(songlist, shuffle, repeat, override)
  File "/usr/lib/python3.10/site-packages/mps_youtube/player.py", line
79, in play
    self._playsong()
  File "/usr/lib/python3.10/site-packages/mps_youtube/player.py", line
138, in _playsong
    self._launch_player()
  File "/usr/lib/python3.10/site-packages/mps_youtube/player.py", line
298, in _launch_player
    self.launch_player(cmd)
  File "/usr/lib/python3.10/site-packages/mps_youtube/players/mpv.py",
line 135, in launch_player
    self._player_status(self.songdata + "; ", self.song.length)
  File "/usr/lib/python3.10/site-packages/mps_youtube/players/mpv.py",
line 188, in _player_status
    if resp['data'] is not None:
KeyError: 'data'
```
After reading some other issues I just decide to switch on `cvlc`. Both in `cvlc` and `vlc` I'm getting audio but no video at all. I have no idea what I'm doing wrong. Thanks in advance for helping guys.

**Comment by iamtalhaasghar** [comment]
There is already a pull request #1172 open for this issue. And i have applied this patch in my fork, namely [yewtube](https://github.com/iamtalhaasghar/yewtube/).

**Comment by iamtalhaasghar** [comment]
was fixed https://github.com/iamtalhaasghar/yewtube/commit/7966a7a9178ecd3a87ae6dcb10f5fce45551d776
