### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by KiskaSasiska** [mps-youtube/mps-youtube#1197]
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "mps_youtube\streams.py", line 180, in _preload
  File "mps_youtube\streams.py", line 51, in get
  File "mps_youtube\util.py", line 205, in get_pafy
  File "site-packages\pafy\pafy.py", line 124, in new
  File "site-packages\pafy\backend_youtube_dl.py", line 29, in __init__
  File "site-packages\pafy\backend_shared.py", line 96, in __init__
  File "site-packages\pafy\backend_youtube_dl.py", line 38, in _fetch_basic
  File "site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "site-packages\youtube_dl\extractor\common.py", line 500, in extract
  File "site-packages\youtube_dl\extractor\youtube.py", line 1613, in _real_extract
TypeError: argument of type 'NoneType' is not iterable

When I try to search for a song, I get a similar error and does not allow me to turn on the music.
Please help me, I do not know what to do.

**Comment by ElizabethWega** [comment]
I have the same issue. :/

**Comment by kenderperez** [comment]
i have the same problem

**Comment by iamtalhaasghar** [comment]
visit #1191
