### ISSUE TITLE
Can't start mpsyt :/

### ISSUE THREAD

**Issue by XelionXS** [mps-youtube/mps-youtube#329]
xelion@Xelion-PC:~$ mpsyt
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 54, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request
xelion@Xelion-PC:~$

**Comment by ids1024** [comment]
Python 2 support was dropped. Use Python 3.

**Comment by XelionXS** [comment]
I've used Python 3.4

**Comment by ids1024** [comment]
Python 2.7 is shown on the output you posted. You should install with pip3 rather than pip so it installs in Python 3 rather than 2.

**Comment by XelionXS** [comment]
Thanks, that's work fine :)
