### ISSUE TITLE
How to play audio only?

### ISSUE THREAD

**Issue by IonicaBizau** [mps-youtube/mps-youtube#333]
Thanks for the nice app! However I'm still confused how to use it.

I used `/oak ridge boys` to search some music and then I saw the items. I want to play them all (like a playlist). How can I do that?

I tried `pl 1` but I've got `Invalid syntax. Enter h for help`. Also, I only need to play the audio part, no video.

**Comment by IonicaBizau** [comment]
Ha! I found it. Just wrote `all` and the magic happened. :sparkles: Maybe would be nice to document these common usages. :smile:

**Comment by lol768** [comment]
```
      Downloading and Playback
  
      set show_video true - play video instead of audio.
  
      <number(s)> - play specified items, separated by commas.
                    e.g., 1-3,5 plays items 1, 2, 3 and 5
  
      d <number> - view downloads available for an item.
      da <number(s)> - download best available audio file(s).
      dv <number(s)> - download best available video file(s).
      dapl <url or id> - download YouTube playlist (audio) by url or id.
      dvpl <url or id> - download YouTube playlist (video) by url or id.
      daupl <username> - download user's YouTube playlists (audio).
      dvupl <username> - download user's YouTube playlists (video).
      dlurl <url or id> download a YouTube video by url or video id.
      playurl <url or id> play a YouTube video by url or id.
  
      ➡ all or * - play all displayed items.
      repeat <number(s)> - play and repeat the specified items.
      shuffle <number(s)> - play specified items in random order.
```

Perhaps it could be more prominent somewhere though

**Comment by IonicaBizau** [comment]
@lol768 I've got it! This tool is :cool:!

**Comment by phoenix84pl** [comment]
I would also ask "how to" and if it is not possible to add the feature:

I want to do a search and play from single line so I can do some automated scripts connected with my voice recognition... so I can play youtube song by saying its title to microphone...

something like:
mpsyt play search blabla 1

**Comment by ritiek** [comment]
@phoenix84pl
```
$ mpsyt .title, 1
```

**Comment by phoenix84pl** [comment]
ritiek: great! very good! thank you...
yesteday somebody told me:

`echo 1 | mpsyt /musictitle`

it also works...

but I found a bug... it does not matter which method I use... with most of the videos I get that instead of sound:

> Exception in thread Thread-1:                                                                                                                     
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3497, in preload
    stream = get_streams(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

> Traceback (most recent call last):                                                                                                                
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4780, in main
    if matchfunction(k, v, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4680, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3450, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3543, in play_range
    returncode = playsong(song, override=override)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 2104, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3497, in preload
    stream = get_streams(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

the same guy who gave me that other solution told me:

> yea the program ends, but if u setup nohup or task-spooker on your mpsyt player config (e.g nohup mpv or tsp mpv ....etc) then it will detach and play b4 the mpsyt program closes. Else just submit a feature request on their github page

I do not understand how to do that :), so I submit a request "on their github page"

thx in advance

**Comment by ritiek** [comment]
@phoenix84pl I am not sure what the other guy meant but this is a problem `mpsyt` is facing to fetch audio streams. Try upgrading your `youtube-dl`.
```
pip3 install youtube-dl -U
```

**Comment by phoenix84pl** [comment]
Thx for reply!

The error log is shorter (so it somehow helped), but still exists :) (and still no sound)

> Traceback (most recent call last):                                                                                                                
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4780, in main
    if matchfunction(k, v, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4680, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3450, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3543, in play_range
    returncode = playsong(song, override=override)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 2104, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

**Comment by ritiek** [comment]
Your `mpsyt` version seems behind as well. Installing it directly from the develop branch may help.

I am not sure what else might cause this error. :confused:

**Comment by phoenix84pl** [comment]
I was installing from Ubuntu/Debian repository and it showed that it is up to date...
but I see on github there is newer version, but I do not know how to install it...
I first removed my ubuntu version through
`sudo apt autoremove mps-youtube`
and next i follow instructions from github:
`pip3 install mps-youtube`
`pip3 install youtube-dl`
`pip3 install dbus-python pygobject`
so when everything is installed i tried:
`mpsyt blabla` - no such file or directory
`mpsyoutube blabla` - no command
`mps-youtube blabla` - no command

so i do not know hot use it at all this way...

k.

**Comment by adrianmrit** [comment]
You can install mps-youtube with pip and from Github with this, if it's
Python 2 they just change pip3 for pip:

sudo pip3 install -U git+https://github.com/mps-youtube/mps-youtube.git

**Comment by phoenix84pl** [comment]
it seems it install correctly, but I do not know how to use it...

`sudo pip3 install -U git+https://github.com/mps-youtube/mps-youtube.git
[sudo] hasło użytkownika phoenix: 
The directory '/home/phoenix/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/phoenix/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/mps-youtube/mps-youtube.git
  Cloning https://github.com/mps-youtube/mps-youtube.git to /tmp/pip-fi5lpzzn-build
Requirement already up-to-date: pafy!=0.4.0,!=0.4.1,!=0.4.2,>=0.3.82 in /home/phoenix/.local/lib/python3.5/site-packages (from mps-youtube===0.2.7.1)
Installing collected packages: mps-youtube
  Found existing installation: mps-youtube 0.2.7.1
    Uninstalling mps-youtube-0.2.7.1:
      Successfully uninstalled mps-youtube-0.2.7.1
  Running setup.py install for mps-youtube ... done
Successfully installed mps-youtube-0.2.7.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`
`phoenix@V3550:~/www/lilion/witryny/domobot/mowa$ mps-youtube blabla`
`mps-youtube: nie znaleziono polecenia` ← means that command not found

**Comment by lol768** [comment]
Binary name should be `mpsyt`, @phoenix84pl - even when pip installed.

**Comment by phoenix84pl** [comment]
$ mpsyt blabla
bash: /usr/bin/mpsyt: Nie ma takiego pliku ani katalogu ← means no such file nor directory

**Comment by ritiek** [comment]
@phoenix84pl Run these commands:

```
$ sudo apt purge -y mps-youtube
$ sudo pip3 uninstall mps-youtube
$ sudo rm /usr/bin/mpsyt /usr/bin/local/mpsyt
$ sudo pip3 install -U git+https://github.com/mps-youtube/mps-youtube.git
$ mpsyt
```

If still error, what is the output of `$ which mpsyt`?

**Comment by phoenix84pl** [comment]
done everything... the most important is last part I believe:

`sudo pip3 install -U git+https://github.com/mps-youtube/mps-youtube.git
The directory '/home/xxx/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/xxx/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/mps-youtube/mps-youtube.git
  Cloning https://github.com/mps-youtube/mps-youtube.git to /tmp/pip-c73h6i56-build
Requirement already up-to-date: pafy!=0.4.0,!=0.4.1,!=0.4.2,>=0.3.82 in ./.local/lib/python3.5/site-packages (from mps-youtube==0.2.7.1)
Installing collected packages: mps-youtube
  Running setup.py install for mps-youtube ... done
Successfully installed mps-youtube-0.2.7.1
xxx@V3550:~$ mpsyt
bash: /usr/bin/mpsyt: Nie ma takiego pliku ani katalogu ← means no such file nor directory
`

**Comment by ritiek** [comment]
@phoenix84pl Try copying `mpsyt` to `/usr/bin/` as well.

```
sudo cp /usr/local/bin/mpsyt /usr/bin/mpsyt
```

**Comment by phoenix84pl** [comment]
done... new errors incomming :)

so now mpsyt hangs straight away... after 5-10secs CTRL-C:

`$ mpsyt /forest
^CTraceback (most recent call last):
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.7.1', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/init.py", line 67, in init
    load_player_info(config.PLAYER.get)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/util.py", line 406, in load_player_info
    g.mpv_version = _get_mpv_version(player)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/util.py", line 444, in _get_mpv_version
    o = subprocess.check_output([exename, "--version"]).decode()
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1059, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt
`
