### ISSUE TITLE
Does not work on ubuntu (15.04 and 15.10)

### ISSUE THREAD

**Issue by erkiha** [mps-youtube/mps-youtube#335]
I get following error when running mpsyt on ubuntu 15.04 and 15.10:

erki@siil:~$ mpsyt 
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 54, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request

**Comment by erkiha** [comment]
reinstalling with pip3 fixed the issue. Maybe its possible to put a message when installing that you need to use a pip3 (python3-pip) on ubuntu. 
sudo aptitude install python3-pip

**Comment by lol768** [comment]
Is it not mentioned here? https://github.com/mps-youtube/mps-youtube/blob/develop/README.rst#installation

**Comment by ids1024** [comment]
There will be such a message. The setup.py file in git gives an error when run with Python 2.

**Comment by erkiha** [comment]
It is, but as I have been long  time user of this program and thought that I do not need to read manual anymore :) It would be more clear if it refuses to install with pip2 or at least should give appropriate message.
