### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by Joesv** [mps-youtube/mps-youtube#343]
'''pi@raspberrypi /etc $ mpsyt
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 54, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request
'''

**Comment by bendem** [comment]
Python 2 is not supported anymore. Try reinstalling it using `pip3`.

**Comment by phra** [comment]
after installing it with pip3, i suggest to install also virtualenv because on some system (e.g. debian jessie) there is python2 set on default.
after doing that, you have to do 'virtualenv-3.4 mpsyt' to set up mpsyt to use python3 and not the default interpreter.

ps: if you change python version from update-alternatives the programs that are only for python2 will not work anymore.

**Comment by ids1024** [comment]
@phra that shouldn't be necessary. Pip3 will set it to use Python 3, whatever the default is.

**Comment by gccpacman** [comment]
Replace it with python3, but it still have some issue

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 96, in <module>
    locale.setlocale(locale.LC_ALL, "")  # for date formatting
  File "/usr/lib/python3.4/locale.py", line 592, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Did I set something wrong?

**Comment by ids1024** [comment]
@gccpacman That is not the same issue (the last lines are the relevant ones), but I do not know what the problem is. I have never seen that error before.

**Comment by gccpacman** [comment]
@ids1024 I think my issue is caused by not setting the system locale on my remote VPS. I fixed this by execute this command:  ```sh -c "echo -e 'LANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8' > /etc/default/locale". ```

**Comment by paapu68** [comment]
Hei,
You could add a warning for people trying to use python2. Something like
> if sys.version_info >= (3, 0):
in case others are as stupid as I and try to use python2 
(yes, the manual is very clear, but one should read it)
Cheers, Markus

**Comment by ids1024** [comment]
@paapu68 Something like that is already in git (0f83e42951a49871a550e4305429081cca35174d), it's just that there hasn't been a release since then.

**Comment by paapu68** [comment]
Ok, Thanks's for great work guys!!!!
