### ISSUE TITLE
ImportError: cannot import name 'g'

### ISSUE THREAD

**Issue by StylinGreymon** [mps-youtube/mps-youtube#364]
when trying to run mpsyt, I get this error:
[~]$ mpsyt                
Traceback (most recent call last):
  File "/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 58, in <module>
    from . import terminalsize, g, c, cache, streams
  File "/usr/lib/python3.4/site-packages/mps_youtube/g.py", line 8, in <module>
    from .playlist import Playlist
  File "/usr/lib/python3.4/site-packages/mps_youtube/playlist.py", line 6, in <module>
    from . import g
ImportError: cannot import name 'g'

This is with 2.6.

**Comment by ids1024** [comment]
I see the cause. I reverted the last two commits, which should fix this.

I wonder why I didn't get the same error? Maybe it is because my computer has python 3.5...
