### ISSUE TITLE
ImportError: No module named 'UserList'

### ISSUE THREAD

**Issue by nishanthkarthik** [mps-youtube/mps-youtube#366]
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/__init__.py", line 2, in <module>
    init()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 868, in init
    init_cache()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 1040, in init_cache
    cached = pickle.load(cf)
ImportError: No module named 'UserList'

I get this error in Ubuntu 15.10
Python 3.4.3+

**Comment by nishanthkarthik** [comment]
Changing 

`#!/usr/bin/python3` in `/usr/local/bin/mpsyt`

to 

`#!/usr/bin/python3.5` fixes the issue.
