### ISSUE TITLE
mpsyt terminates with exception when trying to play a video

### ISSUE THREAD

**Issue by viktornonov** [mps-youtube/mps-youtube#378]
Steps to reproduce: (set_video is false)
1. Open mpsyt
2. Type /jello biafra and school
3. Press Enter
4. Type 1, press enter

    Traceback (most recent call last):

      File "/usr/local/bin/mpsyt", line 9, in <module>
        load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
      File "/usr/local/lib/python3.4/site-packages/mps_youtube/main.py", line 4780, in main
        if matchfunction(k, v, userinput):
      File "/usr/local/lib/python3.4/site-packages/mps_youtube/main.py", line 4680, in matchfunction
        func(*matches)
      File "/usr/local/lib/python3.4/site-packages/mps_youtube/main.py", line 3450, in play
        play_range(songlist, shuffle, repeat, override)
      File "/usr/local/lib/python3.4/site-packages/mps_youtube/main.py", line 3543, in play_range
        returncode = playsong(song, override=override)
      File "/usr/local/lib/python3.4/site-packages/mps_youtube/main.py", line 2104, in playsong
        get_streams(song, force=failcount, callback=writestatus)
      File "/usr/local/lib/python3.4/site-packages/mps_youtube/main.py", line 345, in get_streams
        p = get_pafy(vid, force=force, callback=callback)
      File "/usr/local/lib/python3.4/site-packages/mps_youtube/main.py", line 314, in get_pafy
        p = pafy.new(item.ytid, callback=callback_fn)
      File "/usr/local/lib/python3.4/site-packages/pafy/pafy.py", line 145, in new
        return Pafy(url, basic, gdata, signature, size, callback)
      File "/usr/local/lib/python3.4/site-packages/pafy/pafy.py", line 1076, in __init__
        self.fetch_basic()
      File "/usr/local/lib/python3.4/site-packages/pafy/pafy.py", line 1102, in fetch_basic
        smaps, js_url, funcs, dashurl = get_js_sm(self.videoid)
      File "/usr/local/lib/python3.4/site-packages/pafy/pafy.py", line 704, in get_js_sm
        mainfunc = _get_mainfunc_from_js(javascript)
      File "/usr/local/lib/python3.4/site-packages/pafy/pafy.py", line 364, in _get_mainfunc_from_js
        function = _extract_function_from_js(funcname, js)
      File "/usr/local/lib/python3.4/site-packages/pafy/pafy.py", line 339, in _extract_function_from_js
        args, body = m.groups()
    AttributeError: 'NoneType' object has no attribute 'groups'

This happens only to some of the videos. Some of the other videos are opening fine.
As far as I investigated in the method "_extract_function_from_js" it searches for function called __Zq__, then it doesn't find it and crash. Not sure if the bug is in Pafy or Mpsyt.

The video that fails to open is:
Jello Biafra and the Guantanamo School of Medicine (full cd)

My setup:
OSX 10.10
boto (2.30.0)
pafy (0.4.2)
pip (7.1.2)
Pygments (1.6)
s3funnel (0.6.5)
setuptools (18.3.1)
vboxapi (1.0)
wheel (0.26.0)
workerpool (0.9.2)
youtube-dl (2015.11.10)

Not sure if this is related to #3

**Comment by ids1024** [comment]
> pafy (0.4.2)

Are you sure about that? `_extract_function_from_js()` (as well as `get_js_sm()` and `_get_mainfunc_from_js()`) does not exist in pafy starting with version 0.4 (which uses youtube-dl for that functionality).

It looks to me like you are using an old version of pafy. `mpsyt --version` will show the version mpsyt is using.

**Comment by viktornonov** [comment]
You were right - mpsyt used pafy 0.3.74, so after running:

    sudo pip3 install mps-youtube --upgrade

the video is playing okay. Thank you @ids1024 . The interesting thing is why some of the videos were playing okay with the old version of pafy.
