### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by Tuplad** [mps-youtube/mps-youtube#395]
Used to work fine until I upgraded
sudo pip install --upgrade mps-youtube

All went well, when trying to start:
```
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 54, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request
```

**Comment by ids1024** [comment]
mps-youtube is now Python 3 only.

**Comment by Tuplad** [comment]
Installed python3-pip, removed all packages with pip, installed it again.

vlad@atmosphere-MS-7592:~$ sudo pip3 install mps-youtube --upgrade
Downloading/unpacking mps-youtube from https://pypi.python.org/packages/source/m/mps-youtube/mps-youtube-0.2.5-2.tar.gz#md5=d131d01908c3c9758140152d97832110
  Downloading mps-youtube-0.2.5-2.tar.gz (54kB): 54kB downloaded
  Running setup.py (path:/tmp/pip-build-ivv5yfno/mps-youtube/setup.py) egg_info for package mps-youtube
    
Requirement already up-to-date: pafy>=0.3.74 in /usr/local/lib/python3.4/dist-packages (from mps-youtube)
Installing collected packages: mps-youtube
  Found existing installation: mps-youtube 0.2.5
    Uninstalling mps-youtube:
      Successfully uninstalled mps-youtube
  Running setup.py install for mps-youtube
    
    Installing mpsyt script to /usr/local/bin
Successfully installed mps-youtube
Cleaning up...
vlad@atmosphere-MS-7592:~$ mpsyt
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/__init__.py", line 2, in <module>
    init()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 896, in init
    g.mpv_version = get_mpv_version(Config.PLAYER.get)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 211, in get_mpv_version
    o = subprocess.check_output([exename, "--version"]).decode()
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['mpv', '--version']' returned non-zero exit status -11

**Comment by ids1024** [comment]
@Tuplad What happens when you run `mpv --version` in the terminal?

**Comment by Tuplad** [comment]
Segmentation fault (core dumped)

**Comment by ids1024** [comment]
@Tuplad In that case, it seems something is wrong with mpv.

**Comment by Tuplad** [comment]
Ok, I figured how to install all of it. Had to remove everything through pip3 and aptitude, then reinstall again with both.

Managed to start a song, but now getting the following error:
```
ERROR: Signature extraction failed: Traceback (most recent call last):                                                          
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

The song is palying though.

**Comment by ids1024** [comment]
That is due to a recent change in YouTube. Do you have the latest youtube-dl version?

**Comment by Tuplad** [comment]
1:2015.12.13-1

**Comment by ids1024** [comment]
@Tuplad I believe it should be fixed in youtube_dl 2015.12.18, the release after what you have.

**Comment by Tuplad** [comment]
Just upgraded, still the same error:
```
> ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by ids1024** [comment]
That's strange. Did you restart mps-youtube after updating youtube_dl?

**Comment by Wildefyr** [comment]
Can confirm I've been getting the same error as Tuplad, there are no updates available for pafy or youtube-dl for me either.

**Comment by Tuplad** [comment]
@ids1024 Yes.

**Comment by ids1024** [comment]
Hm, I don't know why this is happening. Is it for any specific video, or every one?

**Comment by Explouad** [comment]
I'm having this issue also. Everything is newly upgraded, including youtube-dl.
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output
```

**Comment by Tuplad** [comment]
@ids1024 I don't play videos, just music.

mpsyt
.artist
1

The error happens before I start playing the song, also after.

**Comment by ids1024** [comment]
Are you sure the python3 copy of youtube_dl is up to date?

**Comment by Tuplad** [comment]
Whoa, I just installed it through "pip3 install youtube-dl" and everything works fine.

Should I keep the packages from apt, or only the pip3 ?

**Comment by ids1024** [comment]
For mpsyt anyway, the one from pip3 is all you will need, though the other shouldn't cause any harm. Hopefully the package from apt will be updated to use python 3 before too long.

**Comment by ids1024** [comment]
@zgrimshell Do you know if the maintainer of the youtube-dl package has plans to move to python 3?
