### ISSUE TITLE
ImportError: cannot import name 'call_gdata' on Windows

### ISSUE THREAD

**Issue by GijsTimmers** [mps-youtube/mps-youtube#400]
After cloning the `mps-youtube` git repository:

```
C:\Python34\Scripts\mps-youtube>C:\Python34\python.exe mpsyt
Traceback (most recent call last):
  File "mpsyt", line 2, in <module>
    import mps_youtube
  File "C:\Python34\Scripts\mps-youtube\mps_youtube\__init__.py", line 1, in <mo
dule>
    from .main import init
  File "C:\Python34\Scripts\mps-youtube\mps_youtube\main.py", line 59, in <modul
e>
    from pafy import call_gdata, GdataError
ImportError: cannot import name 'call_gdata'

C:\Python34\Scripts\mps-youtube>
```

FYI, this was on the `develop` branch.

**Comment by ids1024** [comment]
Hm, somehow I hadn't seen this issue until today. You need to update pafy.

**Comment by GijsTimmers** [comment]
Thank you, that worked.
