### ISSUE TITLE
exits error when done playing a song

### ISSUE THREAD

**Issue by Joseph65** [mps-youtube/mps-youtube#410]
im getting an error when done playing a song exits mpsyt

Traceback (most recent call last):03:31 [100%] [================>] vol: 22%  
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 3695, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 3644, in matchfunction
    func(*matches)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 2427, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 2519, in play_range
    returncode = playsong(song, override=override)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 1187, in playsong
    returncode = launch_player(song, songdata, cmd)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 1305, in launch_player
    sockpath=sockpath)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 1379, in player_status
    elapsed_s = int(resp['data'])
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by Joseph65** [comment]
i just changed the player from mpv to mplayer and it doesnt exit so the problem must be with mpv related

**Comment by ids1024** [comment]
Yes, that code is specific to mpv.

What version of mpv are you using?

**Comment by Joseph65** [comment]
mpv 0.13.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

**Comment by ids1024** [comment]
0.14.0 is the latest version, so perhaps that would fix it?

**Comment by TingoL** [comment]
I've had the same problem. Here's what I did:

renamed the .mpv folder so that mpv would start with defaults. 
Result = it worked.
After narrowing down the culprit among the options I have found that the
**loop=inf**
option in the config file was the one causing the exit after a song.
@Joseph65 You should try it and close this if it works
