### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by spvkgn** [mps-youtube/mps-youtube#422]
Error that I have noticed today, mpsyt and pafy upgraded from latest dev zip
```
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 3401, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 3345, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 2118, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 2210, in play_range
    returncode = playsong(song, override=override)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 1136, in playsong
    cmd, songdata = generate_real_playerargs(song, override, failcount)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 1016, in generate_real_playerargs
    stream = streams.select(cached, q=failcount, audio=(not video), m4a_ok=m4a)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/streams.py", line 99, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/streams.py", line 99, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/streams.py", line 83, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range
```
```
mpsyt version  : 0.2.6
   notes       : released 1 January 2016
pafy version   : 0.4.3
Python version : 3.2.3 (default, Jun 18 2015, 21:46:42) 
[GCC 4.6.3]
Processor      : i686
Machine type   : i686
Architecture   : 32bit, ELF
Platform       : Linux-3.13.0-68-generic-i686-with-LinuxMint-13-maya
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /home/pavel/.config/mps-youtube
env:TERM       : screen-256color
env:SHELL      : /bin/bash
env:LANG       : ru_RU.UTF-8
```

**Comment by ids1024** [comment]
Same as #421. I don't know why this is happening and have yet to reproduce it.

Does downgrading pafy to 0.3.82 fix it?

**Comment by ids1024** [comment]
I think I found the problem, fixed on a branch of pafy: https://github.com/mps-youtube/pafy/tree/fixmpsyt422

@spvkgn Could you test it and see if it works?

**Comment by dlo21** [comment]
I'd been having the same issue, too. I replaced pafy with the branch version and it seems to be fixed on my end.

**Comment by spvkgn** [comment]
@ids1024 Thanks, it works with this fix.

**Comment by ids1024** [comment]
Ok, I merged it into pafy develop.

**Comment by mjonyh** [comment]
I am still getting this error!

**Comment by ids1024** [comment]
@mjonyh Install the git version of pafy and run `clearcache`.

**Comment by mjonyh** [comment]
Thanks. it works. What I want to mention it here is that I got the same error after installed pafy and doing clearcache. Than got angry and press "enter". And found that error gone! cool...
