### ISSUE TITLE
Couldn't search any video

### ISSUE THREAD

**Issue by AnakTeka** [mps-youtube/mps-youtube#428]
`> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 2056, in _preload
    stream = streams.select(streamlist, audio=not video, m4a_ok=m4a)
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 99, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 99, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 83, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range
`

This is happening when trying to search something

youtube-dl 2016.02.01
mpsyt was installed from https://aur.archlinux.org/packages/mps-youtube-git/

> mpsyt version  : 0.2.6
> notes       : released 1 January 2016
> pafy version   : 0.4.3
> Python version : 3.5.1 (default, Dec  7 2015, 12:58:09) 
> [GCC 5.2.0]
> Processor      : 
> Machine type   : x86_64
> Architecture   : 64bit, ELF
> Platform       : Linux-4.3.3-3-ARCH-x86_64-with-arc

Thanks in advance

**Comment by ids1024** [comment]
Looks like the same issue as #422 and #427. Update pafy to git and it should be fixed.

**Comment by AnakTeka** [comment]
Thank you, fixed by updating the pafy package.
