### ISSUE TITLE
mps-youtube installed from pip3 totally broken

### ISSUE THREAD

**Issue by jiang-qian** [mps-youtube/mps-youtube#430]
I install mps-youtube and its dependency via pip3 on a ubuntu 14.04 (python 3.4) 64 bit installation:
pip3 install youtube-dl
pip3 install pafy
pip3 install mps-youtube
The mps-youtube installed is 2.6.2
However, when I search anything, I have the following error. Trying to play a particular video crash the mps-youtube. My pafy version is 4.3, youtube-dl is 2016.02.05-1 and mps-youtube is 2.6.2. As I said, they're all from pip3

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2475, in _preload
    stream = streams.select(streams.get(song), audio=not video, m4a_ok=m4a)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 93, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range

**Comment by jiang-qian** [comment]
I install the development version of pafy from github page. Now searching for items works, but when I try to select an entry by entering the number, it still shows the same error.
> Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2475, in _preload
    stream = streams.select(streams.get(song), audio=not video, m4a_ok=m4a)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 93, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range

**Comment by ids1024** [comment]
This should be fixed in pafy develop, and it is odd for the issue to continue with it.

**Comment by jiang-qian** [comment]
I downloaded the latest zip file from here
https://github.com/mps-youtube/pafy
(download zip button) and installed using ./setup.py install as root.
My mps-youtube is from pip3 (2.6.2). The latest .zip file of mps-youtube doesn't run at all:
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube-0.2.6-py3.4.egg/mps_youtube/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube-0.2.6-py3.4.egg/mps_youtube/main.py", line 62, in <module>
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube-0.2.6-py3.4.egg/mps_youtube/screen.py", line 6, in <module>
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube-0.2.6-py3.4.egg/mps_youtube/content.py", line 3, in <module>
ImportError: cannot import name 'screen

**Comment by jiang-qian** [comment]
Do you know anything I can do about it?

**Comment by jiang-qian** [comment]
I see that I might have some problem with pafy development edition. I tried to install from the zip file by doing ./setup.py install, but it keeps installing for python2.7 (I have both python-2.7 and python-3.4), whereas all my mps-youtube and youtube-dl are installed for python3.4 (using pip3).

How do I force the pafy setup.py script to install for python3.4?

**Comment by ids1024** [comment]
`python3 setup.py install`

**Comment by jiang-qian** [comment]
Thanks! Now I installed pafy development branch zip on python 3.4. No dice:
When I use the stable 2.6.2 mpsyt, I can search, but selecting a specific entry give the same error.
When I use the development zip file, mpsyt crashes on start up with the error above.

**Comment by jiang-qian** [comment]
Now I'm extremely confused. I just checked that when I do
python setup.py install
in the directory that comes from the unzipped pafy-development zip file, under
/usr/local/lib/python3.4/dist-packages/
I only get pafy.egg file, rather than the whole directory containing all other pafy file.

What am I doing wrong? Maybe I'm just too primitive to play with the development branch. Perhaps I should just wait till the fix is released in the stable version and install with pip3...

**Comment by ids1024** [comment]
You can try installing with pip: "sudo pip3 install -U https://github.com/mps-youtube/pafy/archive/develop.zip"

**Comment by jiang-qian** [comment]
Thanks! Now that I that successfully install pafy development zip. I am trying to install mps-youtube development branch:
sudo install -U https://github.com/mps-youtube/archive/develop.zip
but it didn't work. What is the correct url?

**Comment by ids1024** [comment]
https://github.com/mps-youtube/mps-youtube/archive/develop.zip

The error you got with the git version of mps-youtube is due to circular dependencies between source files in the current git, which I hadn't noticed because python3.5 seems to handle that differently. That needs to be fixed... not sure the best way.

**Comment by jiang-qian** [comment]
Thank you for debugging these. If it is not too much trouble, perhaps you could post on this issue when you fix it in the development branch? That way I can try it out.
mpsyt is one program I use everyday, so it'll be nice to get it working again!
Thanks again for looking into this!

**Comment by Scott-Fischer** [comment]
I have this same issues on OSX when using the above install methods

**Comment by ids1024** [comment]
With https://github.com/mps-youtube/mps-youtube/commit/3db14b4c3ddec574de6b71d439ca532fe9fa1aca the install from git should work.

**Comment by jiang-qian** [comment]
Yes, mys-youtube does start correctly now. However, it still does not work when I try to play video.
To reproduce: search for a video, such as /snl then try to play the first item by typing 1.
The video briefly appears but then disappears, and mpsyt crashes with these errors:

Traceback (most recent call last):                                              
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3289, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3229, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2007, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2099, in play_range
    returncode = playsong(song, override=override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 1146, in playsong
    returncode = launch_player(song, songdata, cmd)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/player.py", line 122, in launch_player
    sockpath=sockpath)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/player.py", line 247, in _player_status
    screen.writestatus(line)
NameError: name 'screen' is not defined

I assume this is similar to the error you just fixed? Should I file a new bug or perhaps it is easy for you to just fix it?

For debugging, my player is mpv and it plays things just fine before.

Thank you again for looking into this.

**Comment by ids1024** [comment]
@jiang-qian Ok, fixed that in https://github.com/mps-youtube/mps-youtube/commit/ddb793b13f146fe06c88f55893ebdda561db8b4b. Hopefully it is working now.

**Comment by jiang-qian** [comment]
Yes it does! Thank you so much! A week without mys-youtube just made me realize how much convenience it brings me everyday! Thank you again for developing this!

**Comment by uNouss** [comment]
hello
i think i have same issue, i have ubuntu 14.04 too but 32bit installation
here my config

hello, I get errors when I try some terms like this

![](https://framapic.org/s5icrYqqdCsX/ZIdjnyoMbtGn)

here is my config

![](https://framapic.org/CkY7bYx46bmW/EBhy50XbFSld) 

P.S: I'm updating to the latest version of development and still have the same errors for some searches.

**Comment by ids1024** [comment]
@uNouss Did you update pafy to develop or just mpsyt? The fix for that is in pafy, so you need to update that.

**Comment by uNouss** [comment]
@ids1024 i update pafy and mpsyt to develop but I noticed that it happens most often when the terminal window is small like first capture

**Comment by raidentel** [comment]
Hello i m running under Debian 64bit, i have resmax error, i have pafy and everything updated , i use python3.4, this error raise when i tried to make a search

**Comment by vnckppl** [comment]
I am on OSX as well and have installed mpsyt and pafy develop but still experience the same problems. Is there a solution available yet?

**Comment by ids1024** [comment]
It should be fixed by using pafy git and running `clearcache` in mpsyt.

**Comment by vnckppl** [comment]
Yes, clearing the cache did it for me.

Thank you.
