### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by orbea** [mps-youtube/mps-youtube#434]
os: Slackware-current

mps-youtube: 0f56b70_2016.02.06
pafy: b1e7bfd_2016.01.29
youtube-dl: 2016.02.10

When searching like: `$ mpsyt /lorne green ringo`
```
Search results for lorne green ringo                      [1/10>
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.5/site-packages/mps_youtube/main.py", line 2056, in _preload
    stream = streams.select(streamlist, audio=not video, m4a_ok=m4a)
  File "/usr/lib64/python3.5/site-packages/mps_youtube/streams.py", line 99, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/lib64/python3.5/site-packages/mps_youtube/streams.py", line 99, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/lib64/python3.5/site-packages/mps_youtube/streams.py", line 83, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range
```

**Comment by orbea** [comment]
This seems to have been a youtube-dl issue, it was solved with youtube-dl-2016.02.13.

I will close this issue for now.
