### ISSUE TITLE
when i try to open a video  

### ISSUE THREAD

**Issue by nadeemohd** [mps-youtube/mps-youtube#439]
Invalid item / range entered!                       [1/25>
> Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2475, in _preload
    stream = streams.select(streams.get(song), audio=not video, m4a_ok=m4a)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 93, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range

**Comment by ids1024** [comment]
See https://github.com/mps-youtube/mps-youtube/issues/422.

Try updating pafy and mpsyt to the git version with `sudo pip3 install --upgrade https://github.com/mps-youtube/pafy/archive/develop.zip https://github.com/mps-youtube/mps-youtube/archive/develop.zip`.

**Comment by nadeemohd** [comment]
Thanks Allot but it was not the problem of mpsyt but the problem was due to mplayer which was not supporting and also causing this problem when i typed set player mpv and changed my player it is now working perfectly ..thanks
