### ISSUE TITLE
IndexError after setting show_video to True

### ISSUE THREAD

**Issue by GijsTimmers** [mps-youtube/mps-youtube#445]
Running `mps-youtube` v. 0.2.6 on Ubuntu 15.10, installed via `pip3`.

Problem also occurred on Ubuntu 14.04.

After executing

    set show_video True

I get the following error right after entering my search terms:

```
Search results for duke dumont i got u                  [1/25>
> Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2475, in _preload
    stream = streams.select(streams.get(song), audio=not video, m4a_ok=m4a)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 93, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range
```

**Comment by GijsTimmers** [comment]
Duplicates:
- https://github.com/mps-youtube/mps-youtube/issues/422
- https://github.com/mps-youtube/mps-youtube/issues/430
- https://github.com/mps-youtube/mps-youtube/issues/435


https://github.com/mps-youtube/mps-youtube/issues/435#issuecomment-183922136 fixed it:

    sudo pip3 install -U https://github.com/mps-youtube/pafy/archive/develop.zip

**Comment by liborw** [comment]
Still same problem, for both `mplayer` and `mpv`:

```
mpsyt version  : 0.2.6
   notes       : released 1 January 2016
pafy version   : 0.4.3
Python version : 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4]
Processor      : x86_64
Machine type   : x86_64
Architecture   : 64bit, ELF
Platform       : Linux-3.13.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /home/wagnelib/.config/mps-youtube
env:TERM       : xterm
env:SHELL      : /usr/bin/zsh
env:LANG       : en_US.UTF-8
env:LANGUAGE   : en_US
```

```
Search results for test                                         [1/13>
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2475, in _preload
    stream = streams.select(streams.get(song), audio=not video, m4a_ok=m4a)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 109, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 93, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range
```
