### ISSUE TITLE
Ubuntu Upgrade 15.04 to 15.10 broke mpsyt (won't start)

### ISSUE THREAD

**Issue by lmhsjackson** [mps-youtube/mps-youtube#451]
Hi I was running mpsyt ok in ubuntu 15.04, after upgrading to 15.10 I got the following error.

Tried reinstalling the package via pip, and still the same.

```
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/__init__.py", line 2, in <module>
    init()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 243, in init
    cache.load()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/cache.py", line 21, in load
    cached = pickle.load(cf)
ImportError: No module named 'UserString'
```

**Comment by ids1024** [comment]
Try running `rm ~/.config/mps-youtube/cache_py_*`.

**Comment by lmhsjackson** [comment]
Worked perfectly. Thank you very much!

**Comment by georg8** [comment]
Hi I was running mpsyt on Ubuntu 14.04 I got the following error.

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2475, in _preload
    stream = streams.select(streams.get(song), audio=not video, m4a_ok=m4a)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/streams.py", line 50, in get
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/util.py", line 175, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 125, in new
    return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)
  File "/usr/local/lib/python3.4/dist-packages/pafy/backend_internal.py", line 47, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python3.4/dist-packages/pafy/backend_internal.py", line 94, in _fetch_basic
    self.callback)
  File "/usr/local/lib/python3.4/dist-packages/pafy/backend_internal.py", line 433, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'


Meant a lot to me to do, that's a great script.Thanks in advance!  :)

**Comment by ids1024** [comment]
@georg8 What version of pafy do you have? Is youtube_dl installed?

**Comment by georg8** [comment]
Yes is installed youtube-dl.How to see which version pafy?how to install a new version pafy in Ubuntu 14.04? Thanks a lot for your help!!! :)   :+1:

**Comment by ids1024** [comment]
You can see what pafy version is being used (among other things) with `mpsyt --version`.

Using `pip install -U pafy` will update pafy to the latest version.

**Comment by georg8** [comment]
I did it...SUPER! Thank you very much!!! :+1:  :+1:  :+1:  :100:  
You can tell me whether it is possible to play song  a local disk with mpsyt?How to do it?
