### ISSUE TITLE
Cant watch video

### ISSUE THREAD

**Issue by sabastiaan** [mps-youtube/mps-youtube#463]
each time I try to watch any video I get this

Traceback (most recent call last):                                                    
  File "/usr/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 3695, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 3644, in matchfunction
    func(*matches)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 2427, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 2519, in play_range
    returncode = playsong(song, override=override)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 1138, in playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/lib/python3.4/site-packages/mps_youtube/streams.py", line 50, in get
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3.4/site-packages/mps_youtube/util.py", line 175, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 125, in new
    return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)
  File "/usr/lib/python3.4/site-packages/pafy/backend_internal.py", line 47, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3.4/site-packages/pafy/backend_internal.py", line 94, in _fetch_basic
    self.callback)
  File "/usr/lib/python3.4/site-packages/pafy/backend_internal.py", line 433, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

**Comment by ids1024** [comment]
Install `youtube_dl`. If you do have it installed but nothing changes, you need the python 3 version, so install it with `pip3 install youtube_dl`.

**Comment by sabastiaan** [comment]
Ow now I feel stupid, thanks for helping me^_^
