### ISSUE TITLE
Crash on Windows when searching videos by user

### ISSUE THREAD

**Issue by mindbound** [mps-youtube/mps-youtube#469]
When searching with `u $videonumber`, the compiled Windows version of 0.2.6 crashes with

```
Traceback (most recent call last):
  File "mpsyt", line 3, in <module>
  File "E:\Devel\src\git\mps-youtube\mps_youtube\main.py", line 3695, in main
  File "E:\Devel\src\git\mps-youtube\mps_youtube\main.py", line 3644, in matchfunction
  File "E:\Devel\src\git\mps-youtube\mps_youtube\main.py", line 2991, in user_more
TypeError: usersearch_id() takes 1 positional argument but 3 were given
```

(same happens with the pip3-installed one).

**Comment by ids1024** [comment]
This bug should already be fixed in git.
Try `pip3 install https://github.com/mps-youtube/mps-youtube/archive/develop.zip`

**Comment by mindbound** [comment]
Thanks, that solved that.
