### ISSUE TITLE
KeyError: 'dashmpd' in mpsyt

### ISSUE THREAD

**Issue by zensubz** [mps-youtube/mps-youtube#471]
Great program...

Made an upgrade recently to both mps-youtube and pafy (devel). youtube-dl is also up-to-date. Yet, I see the following set of error messages while making a search. mpsyt is functional though - except that I don't feel quite comfortable when this error is displayed. 

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 2475, in _preload
    stream = streams.select(streams.get(song), audio=not video, m4a_ok=m4a)
  File "/usr/lib/python3.4/site-packages/mps_youtube/streams.py", line 50, in get
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3.4/site-packages/mps_youtube/util.py", line 175, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3.4/site-packages/pafy/backend_internal.py", line 42, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3.4/site-packages/pafy/backend_internal.py", line 89, in _fetch_basic
    self.callback)
  File "/usr/lib/python3.4/site-packages/pafy/backend_internal.py", line 425, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

**Comment by zensubz** [comment]
mpsyt was crashing with latest pafy (0.5.0), and I figured out that it might be due to pafy backend setting in my .bashrc file. The following setting (which was actually working for pafy 0.4.3) had to be removed:

export PAFY_BACKEND="internal"

After a system-restart, there was no problem, mpsyt has become fully functional again, the search(es) no longer produce any errors, and no problem with downloads at all... So far so good. 

I think earlier versions of pafy (0.4.3) might require the above .bashrc setting (youtube-dl was also required during manual installation/compilation), whereas with 0.5.0, youtube-dl has been kept as an 'optional' requirement.

My problem (with mpsyt) seems to be solved.
