### ISSUE TITLE
Exception thrown when searching for "minecraft parody"

### ISSUE THREAD

**Issue by mbround18** [mps-youtube/mps-youtube#474]
When you execute the command 'search minecraft parody' an exception is thrown

```
Search results for minecraft paroy                                                             [1/25>
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 1772, in _preload
    streamlist = streams.get(song)
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 50, in get
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3.5/site-packages/mps_youtube/util.py", line 178, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3.5/site-packages/pafy/pafy.py", line 125, in new
    return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)
  File "/usr/lib/python3.5/site-packages/pafy/backend_internal.py", line 47, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3.5/site-packages/pafy/backend_internal.py", line 94, in _fetch_basic
    self.callback)
  File "/usr/lib/python3.5/site-packages/pafy/backend_internal.py", line 433, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
```

When you attempt to select a song from the list the following exception is thrown and the cli client crashes

```
Traceback (most recent call last):                                                                                     
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 3056, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 2993, in matchfunction
    func(*matches)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 1724, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 1816, in play_range
    returncode = playsong(song, override=override)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 774, in playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 50, in get
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3.5/site-packages/mps_youtube/util.py", line 178, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3.5/site-packages/pafy/pafy.py", line 125, in new
    return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)
  File "/usr/lib/python3.5/site-packages/pafy/backend_internal.py", line 47, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3.5/site-packages/pafy/backend_internal.py", line 94, in _fetch_basic
    self.callback)
  File "/usr/lib/python3.5/site-packages/pafy/backend_internal.py", line 433, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
```

**Comment by ids1024** [comment]
Install youtube-dl:
`pip3 install youtube-dl`

**Comment by mbround18** [comment]
That worked for me, thank you
