### ISSUE TITLE
Manjaro  I get Intro error 

### ISSUE THREAD

**Issue by ximi75** [mps-youtube/mps-youtube#483]
I get Intro error can anyone help me

mpsyt
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 61, in <module>
    from . import g, c, commands, cache, streams, screen
  File "/usr/lib/python3.5/site-packages/mps_youtube/cache.py", line 6, in <module>
    from . import g, c, streams
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 5, in <module>
    from .config import Config
  File "/usr/lib/python3.5/site-packages/mps_youtube/config.py", line 274, in <module>
    class _Config(object):
  File "/usr/lib/python3.5/site-packages/mps_youtube/config.py", line 297, in _Config
    ConfigItem("ddir", get_default_ddir(), check_fn=check_ddir),
  File "/usr/lib/python3.5/site-packages/mps_youtube/paths.py", line 24, in get_default_ddir
    lines = open(USER_DIRS).readlines()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 500: ordinal not in range(128)

**Comment by medchedli** [comment]
same issue here but only when using Hyper Terminal 
![capture d ecran de 2017-10-24 12-23-05](https://user-images.githubusercontent.com/3912825/31940507-50f562d6-b8b6-11e7-8d57-2451b952c240.png)
