### ISSUE TITLE
EOFERROR: Ran out of input

### ISSUE THREAD

**Issue by VoltzLive** [mps-youtube/mps-youtube#487]
`Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 119, in main
    history.load()
  File "/usr/lib/python3.5/site-packages/mps_youtube/history.py", line 24, in load
    g.userhist = pickle.load(hlf)
EOFError: Ran out of input`

I'm not really sure what to make of this, I installed it through Yaourt, It worked great, then I restarted, now it doesn't work anymore...

**Comment by ids1024** [comment]
I don't know why this would happen; a corrupted file, I guess. The history file is `~/.config/mps-youtube/play_history`, so you can delete it.

**Comment by mangakah** [comment]
I had the same issue, but it was with the `config.py` file (the file was empty for some reason...). Deleting `~/.config/mps-youtube` solved the problem for me.

```
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/__init__.py", line 2, in <module>
    init()
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/main.py", line 240, in init
    Config.load()
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/config.py", line 340, in load
    saved_config = pickle.load(cf)
EOFError: Ran out of input
```

I think the problem is that **pickle** is loading the file without checking if it is empty first and this exception is raised.

**Comment by ids1024** [comment]
> I think the problem is that pickle is loading the file without checking if it is empty first and this exception is raised.

That is probably the case, if the file is empty. But why did there end up being an empty file? Did mpsyt crash while trying to write to it?

**Comment by mangakah** [comment]
I think so. There's no other program or function messing with these files, right? I'm sure the file was empty, I checked. If I recall correctly, it happened after I interrupted the program using Ctrl+C twice while the player was running, but I couldn't reproduce the error.

**Comment by ids1024** [comment]
Using Ctrl+C triggers a `KeyboardInterrupt` exception, so if mpsyt happens to be writting to a file at the time, that would be interupted.

Hopefully this could be fixed by writting to the history, config, etc. on exit (after `KeyboardInterupt`).

If you pressed ctrl-c twice, the second time may trigger a `KeyboardInterupt` that is not caught. Did it print a traceback with a `KeyboardInterupt` message?

**Comment by mangakah** [comment]
Sorry, if it printed I didn't saved. If it happens again I'll post the traceback here.

**Comment by davidhq** [comment]
I just had the same problem after `mpsyt` stopped after trying to resume a song and the whole system (running on `C.H.I.P.` - RPi like small computer) halted... it disappeared from the network and I had to unplug and restart it... Could the problem be external to `mpsyt` or did the program actually somehow cause the system to freeze? Anyway, after rebooting, `mpsyt` wouldn't run and after I deleted `~/.config/mps-youtube/play_history`, it worked.. that file showed as empty (using `cat`) but on the fs it listed as 1.4KB.

**Comment by T-jw** [comment]
Occurred next time I attempted to load mpsyt after a session when a video could not continue playing due to no more disk space on device.

```
Enter /search-term to search or [h]elp                                          
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.7.1', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.6/site-packages/mps_youtube/main.py", line 119, in main
    history.load()
  File "/usr/lib/python3.6/site-packages/mps_youtube/history.py", line 24, in load
    g.userhist = pickle.load(hlf)
EOFError: Ran out of input

```

**Comment by ids1024** [comment]
Yeah, I don't know if there's anything mpsyt can do to prevent corruption if the disk is full. I guess writing to a temporary file and copying over the original would provide an atomic write... and I don't think that should cause any issue.
