### ISSUE TITLE
Windows xp bug

### ISSUE THREAD

**Issue by doonoo** [mps-youtube/mps-youtube#489]
`CreateProcess: %1 is not a valid Win32 application.
Traceback (most recent call last):
  File "mpsyt", line 3, in <module>
  File "E:\Devel\src\git\mps-youtube\mps_youtube\main.py", line 3695, in main
  File "E:\Devel\src\git\mps-youtube\mps_youtube\main.py", line 3644, in matchfu
nction
  File "E:\Devel\src\git\mps-youtube\mps_youtube\main.py", line 459, in setconfi
g
  File "E:\Devel\src\git\mps-youtube\mps_youtube\config.py", line 139, in set
  File "E:\Devel\src\git\mps-youtube\mps_youtube\config.py", line 264, in check_
player
  File "E:\Devel\src\git\mps-youtube\mps_youtube\config.py", line 250, in check_
player
  File "E:\Devel\src\git\mps-youtube\mps_youtube\util.py", line 43, in get_mpv_v
ersion
  File "C:\Python34\lib\subprocess.py", line 620, in check_output
subprocess.CalledProcessError: Command '['mpv.com', '--version']' returned non-z
ero exit status 1`

Happened with I tried to do `set player mpv`. And I can't click the .exe normally, I have to execute it through cmd just for it to work.

**Comment by ids1024** [comment]
Do you have `mpv.com` in your PATH? You can instead try `set player c:/full/path/to/mpv.com`.

What happens if you run `mpv.com --version` outside mpsyt?

**Comment by doonoo** [comment]
Nevermind, turns out the version of mpv didn't support my windows. Thanks for the help.

**Comment by ids1024** [comment]
Oh, yes, I forgot about that. You can use an older mpv version, before they dropped XP support, or you can use mplayer.
