### ISSUE TITLE
Most music won't play, all music produces errors

### ISSUE THREAD

**Issue by SnoringFrog** [mps-youtube/mps-youtube#500]
*In the process of writing up this bug report, I solved my own issue. Still submitting this in case someone else comes along with the same issue.*

Issue: most music won't play anymore, all music spits out piles of errors from youtube-dl
Fix: [Update youtube-dl](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl), for me it was with `pip install -U youtube-dl` 

Installation details:
- running from Cygwin on Windows
- player is `mpv`, `show_video` set to `false`
- I ran `pip3 install mps-youtube --upgrade` about 10 minutes ago

Most songs, whether they play or not, spit out an error like this ([full log from a non-working song](http://pastebin.com/AzEh0jVh)):
 
> ERROR: Signature extraction failed: Traceback (most recent call last):                                                                                                                                                                                                     ]
>   File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
>     video_id, player_url, s
>   File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
>     res = self._parse_sig_js(code)
>   File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
>     initial_function = jsi.extract_function(funcname)
>   File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
>     raise ExtractorError('Could not find JS function %r' % funcname)
> youtube_dl.utils.ExtractorError: Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError("Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

It was just an issue with `youtube-dl` being out of date, so updating that program cleared everything up.

**Comment by SnoringFrog** [comment]
I'm not entirely sure how the `mpsyt`/`youtube-dl` interaction works codewise, so I'm not sure if there's anything you can do to mitigate this at all, or if it's common enough to warrant mentioning in the Troubleshooting FAQ or anything.
