### ISSUE TITLE
Failed to search when show_video=True

### ISSUE THREAD

**Issue by AnakTeka** [mps-youtube/mps-youtube#507]
I can't seem to load video when I set show_video=True, when show_video=False music load correctly.

Error log

> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 172, in _preload
>     stream = select(streamlist, audio=not video, m4a_ok=m4a)
>   File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 107, in select
>     streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
>   File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 107, in <listcomp>
>     streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
>   File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 84, in okres
>     return int(x['quality'].split("x")[1]) <= maxres
> IndexError: list index out of range

youtube-dl version
>2016.07.09.2

mpsyt version

> mpsyt version      : 0.2.7.1
>  notes           : released 6 July 2016
> pafy version       : 0.5.1 (youtube-dl backend)
> youtube-dl version : 2016.07.09.2
> Python version     : 3.5.2 (default, Jun 28 2016, 08:46:01) 
> [GCC 6.1.1 20160602]
> Processor          : 
> Machine type       : x86_64
> Architecture       : 64bit, ELF
> Platform           : Linux-4.6.3-1-ARCH-x86_64-with-arch
> sys.stdout.enc     : UTF-8
> default enc        : utf-8
> Config dir         : /home/xoxo/.config/mps-youtube
> env:TERM           : rxvt-unicode-256color
> env:SHELL          : /usr/bin/zsh
> env:LANG           : en_US.UTF-8

**Comment by AnakTeka** [comment]
Fixed by deleting files in .config/mps-youtube/
