### ISSUE TITLE
Can't install with pip3

### ISSUE THREAD

**Issue by ErmanSayin** [mps-youtube/mps-youtube#509]
```
erman@erman-ubuntu:~$ pip3 install mps-youtube
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==8.1.2' distribution was not found and is required by the application
```

**Comment by ids1024** [comment]
Are you able to install anything else with pip3? That looks like an issue with your pip install, and not anything to do with mpsyt.

**Comment by Mactepp** [comment]
Try to update the pip, worked for me.

**Comment by ErmanSayin** [comment]
updating worked
