### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by johnwmail** [mps-youtube/mps-youtube#512]
Hi, I installed mpsyt 2.71 from debian package, and crash very often.

Traceback (most recent call last):                                                                                                                                                                              
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.7.1', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/commands/misc.py", line 206, in info
    streams.get(item)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/util.py", line 201, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3/dist-packages/pafy/backend_internal.py", line 42, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/backend_internal.py", line 89, in _fetch_basic
    self.callback)
  File "/usr/lib/python3/dist-packages/pafy/backend_internal.py", line 425, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

**Comment by Ritiek** [comment]
https://pypi.python.org/pypi/pafy/0.4.1

try using pafy 0.4.1,

**Comment by johnwmail** [comment]
Yes, I already installed "python3-pafy 0.5.1-1",
Can I install both pafy 0.4.1 and "python3-pafy 0.5.1-1"?
How to config mpsyt to use pafy 0.4.1?

Thank you.

**Comment by Ritiek** [comment]
okay, first u need to uninstall pafy 0.5.1 and then install pafy 0.4.2
`pip uninstall pafy or pip3 uninstall pafy
wget https://pypi.python.org/packages/source/p/pafy/pafy-0.4.2.tar.gz
(both pafy 0.4.1 and 0.4.2 should work, but i prefer use pafy 0.4.2)
tar -zxvf pafy-0.4.2.tar.gz
cd pafy-0.4.2
sudo python setup.py install or sudo python3 setup.py install`

now try running mpsyt, hopefully it should not give any crashes anymore..

**Comment by ids1024** [comment]
You need to install youtube-dl, but you need the python 3 version (the debian package is python 2 only; hopefully that will change soon). Install it with `pip3 install youtube_dl`.

**Comment by johnwmail** [comment]
Install youtube-dl (python3 version) fixed it, thank all.
