### ISSUE TITLE
Search and playback error

### ISSUE THREAD

**Issue by MealithidX** [mps-youtube/mps-youtube#541]
When i search for some phrases is get following error:

> Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3497, in preload
    stream = get_streams(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

If i press enter then and play a song on the list the following error displays before the program crashes.

Traceback (most recent call last):                                              
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4780, in main
    if matchfunction(k, v, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4680, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3450, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3543, in play_range
    returncode = playsong(song, override=override)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 2104, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3497, in preload
    stream = get_streams(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

**Comment by MealithidX** [comment]
Reinstalled mps and now it seems to work.

**Comment by surajtripathy07** [comment]
@MealithidX  Did you compile the src code?
I am trying it using apt install and the problem still persists even after reinstalling mps-youtube

**Comment by MealithidX** [comment]
Hello Suraj


Sorry, i don't know. I am an absolute newbie when it comes to Linux and was just disappointed because your program was exactly what I wanted to play youtube sound on.


I have since moved away from Linux again.


I am sorry for your inconvenience.


Kind regards.



________________________________

**Comment by ids1024** [comment]
Install with pip, and also install youtube-dl with pip.

`pip3 install mps-youtube youtube-dl`

Then it should work.

**Comment by surajtripathy07** [comment]
@ids1024 I did that and it worked. Thanks.

**Comment by yzexeter** [comment]
Tried every thing above. It does not work at all in windows. Any advice?

**Comment by ritiek** [comment]
@yzexeter Maybe this would help:
```
pip3 install mps-youtube -U
pip3 install youtube-dl -U
pip3 install pafy -U
```
