### ISSUE TITLE
KeyError is thrown for playback

### ISSUE THREAD

**Issue by spacecowboy** [mps-youtube/mps-youtube#542]
## What I did
- Start `mpsyt` from shell
- Enter a search `/brothers of metal`
- Enter `2`, where 2 refers to 

```
Num  Title                                                                                                                                                                  Time
 1   Manowar- Brothers Of Metal                                                                                                                                            03:59
 2   Brothers of Metal - Prophecy of Ragnarök (Lyric Video)                                                                                                                03:43
 3   Manowar - Brothers of Metal (HQ) (Lyrics)                                                                                                                             03:55
 4   Brothers of Metal - Yggdrasil (DEMO)                                                                                                                                  04:30
...
```
## Stacktrace

```
Traceback (most recent call last):                                                                                                                                                 
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/player.py", line 148, in _playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/streams.py", line 56, in get
    [x.url for x in ps]
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/streams.py", line 56, in <listcomp>
    [x.url for x in ps]
  File "/home/jonas/miniconda/lib/python3.5/site-packages/pafy/backend_internal.py", line 236, in url
    self._url = _make_url(self._rawurl, self._sig)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/pafy/backend_internal.py", line 448, in _make_url
    raise IOError("Error retrieving url")
OSError: Error retrieving url

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/player.py", line 148, in _playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/streams.py", line 56, in get
    [x.url for x in ps]
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/streams.py", line 56, in <listcomp>
    [x.url for x in ps]
  File "/home/jonas/miniconda/lib/python3.5/site-packages/pafy/backend_internal.py", line 236, in url
    self._url = _make_url(self._rawurl, self._sig)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/pafy/backend_internal.py", line 448, in _make_url
    raise IOError("Error retrieving url")
OSError: Error retrieving url

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/player.py", line 148, in _playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/streams.py", line 56, in get
    [x.url for x in ps]
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/streams.py", line 56, in <listcomp>
    [x.url for x in ps]
  File "/home/jonas/miniconda/lib/python3.5/site-packages/pafy/backend_internal.py", line 236, in url
    self._url = _make_url(self._rawurl, self._sig)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/pafy/backend_internal.py", line 448, in _make_url
    raise IOError("Error retrieving url")
OSError: Error retrieving url

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonas/miniconda/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/commands/play.py", line 85, in play
    play_range(songlist, shuffle, repeat, override)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/player.py", line 41, in play_range
    returncode = _playsong(song, override=override)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/player.py", line 160, in _playsong
    return _playsong(song, failcount=failcount, override=override)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/player.py", line 160, in _playsong
    return _playsong(song, failcount=failcount, override=override)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/player.py", line 160, in _playsong
    return _playsong(song, failcount=failcount, override=override)
  File "/home/jonas/miniconda/lib/python3.5/site-packages/mps_youtube/player.py", line 175, in _playsong
    cached = g.streams[song.ytid]
KeyError: 'PCpi1sZEZ1U'
```
## Other info
- Installed via `pip`. `pip freeze` reports: `mps-youtube==0.2.7.1`
- `python --version` reports `Python 3.5.2 :: Continuum Analytics, Inc.` (miniconda installation)

**Comment by ids1024** [comment]
What is the full output of `mpsyt --version`?

**Comment by spacecowboy** [comment]
sorry about the delay, this is the output:

```
$ mpsyt --version
WARNING:root:pafy: youtube-dl not found; falling back to internal backend. This is not as well maintained as the youtube-dl backend. To hide this message, set the environmental variable PAFY_BACKEND to "internal".
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.2 (internal backend)
Python version     : 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/jonas/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /usr/bin/zsh
env:LANG           : en_US.utf8
env:LANGUAGE       : en_US:en
```

It is definitely due to the lack of `youtube-dl`. I have the same version of `mpsyt` on my other machine, but with `youtube-dl` installed, and there I can't reproduce the issue.

**Comment by ids1024** [comment]
Yes, installing `youtube-dl` should fix it.
