### ISSUE TITLE
KeyError: 'Qv'

### ISSUE THREAD

**Issue by thelastinuit** [mps-youtube/mps-youtube#545]
any one is having this issue?

tried to play a song. Boom, instant diarrhea
```
Exception in thread Thread-1:                                                                                                                                
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 171, in _preload
    streamlist = get(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/util.py", line 201, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3/dist-packages/pafy/backend_internal.py", line 42, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/backend_internal.py", line 98, in _fetch_basic
    goodsig = _decodesig(dashsig, js_url, self.callback)
  File "/usr/lib/python3/dist-packages/pafy/backend_internal.py", line 342, in _decodesig
    solved = mainfunction([sig])
  File "/usr/lib/python3/dist-packages/pafy/jsinterp.py", line 280, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3/dist-packages/pafy/jsinterp.py", line 81, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/pafy/jsinterp.py", line 200, in interpret_expression
    return obj[member](argvals)
KeyError: 'Qv'

Traceback (most recent call last):                                                                                                                           
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.7.1', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/commands/play.py", line 85, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3/dist-packages/mps_youtube/player.py", line 41, in play_range
    returncode = _playsong(song, override=override)
  File "/usr/lib/python3/dist-packages/mps_youtube/player.py", line 148, in _playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/util.py", line 201, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3/dist-packages/pafy/backend_internal.py", line 42, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/backend_internal.py", line 98, in _fetch_basic
    goodsig = _decodesig(dashsig, js_url, self.callback)
  File "/usr/lib/python3/dist-packages/pafy/backend_internal.py", line 342, in _decodesig
    solved = mainfunction([sig])
  File "/usr/lib/python3/dist-packages/pafy/jsinterp.py", line 280, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3/dist-packages/pafy/jsinterp.py", line 81, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/pafy/jsinterp.py", line 200, in interpret_expression
    return obj[member](argvals)
KeyError: 'Qv'

```

**Comment by thelastinuit** [comment]
Well, I use now the docker verision. Perhaps the issue is something related with linux... :/
