### ISSUE TITLE
mpsyt-0.2.7.1 faile to list downloads available with 2/4 youtube urls I tried

### ISSUE THREAD

**Issue by DoRullings** [mps-youtube/mps-youtube#596]
I tried following command on this url:
dlurl: https://www.youtube.com/watch?v=UNfaNCzgkQk
dlurl https://www.youtube.com/watch?v=A22oy8dFjqc

> ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\youtube_dl\extractor\youtube.py", line 100
> 1, in _decrypt_signature
>   File "C:\Python34\lib\site-packages\youtube_dl\extractor\youtube.py", line 915
> , in _extract_signature_function
>   File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 503,
>  in _download_webpage
>   File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 410,
>  in _download_webpage_handle
>   File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 390,
>  in _request_webpage
>   File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1954, in ur
> lopen
>   File "C:\Python34\lib\site-packages\youtube_dl\utils.py", line 499, in sanitiz
> ed_Request
>   File "C:\Python34\lib\urllib\request.py", line 266, in __init__
>     self.full_url = url
>   File "C:\Python34\lib\urllib\request.py", line 292, in full_url
>     self._parse()
>   File "C:\Python34\lib\urllib\request.py", line 321, in _parse
>     raise ValueError("unknown url type: %r" % self.full_url)
> ValueError: unknown url type: '/yts/jsbin/player-en_US-vflVlxFvV/base.js'
>  (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflVlxFvV/bas
> e.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are
>  using the latest version; type  youtube-dl -U  to update. Be sure to call youtu
> be-dl with the --verbose flag and include its complete output.

It works with this url: https://www.youtube.com/watch?v=kRcVACHAwcE
The bug replicate itself every time I tries to enter the urls above.

Cheer!
//Thomas

**Comment by ids1024** [comment]
I can't seem to reproduce this. Do you have the latest version of youtub-dl?

**Comment by DoRullings** [comment]
Sorry for my late reply! I haven't used mpsyt that much lately, but last time I used it I got the same error on one specific video ID. It has a slight delay before the [Fetching stream info ...  =>] or something like that, when it fails it fails exactly when you expect to see the list of the downloads. I could reproduce that ID several times, but right before I should post my findings here, it suddenly worked with that ID as well. This but seems to be rather random. I wouldn't spend much time on it before more people start reporting it.

**Comment by amitmtrn** [comment]
Hi, I had something similar on ubuntu.
sometimes I get the error once and the song play and sometimes it run the error in loop until keyboard interrupt.


any ideas?

```
ERROR: Signature extraction failed: Traceback (most recent call last):          
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

mpsyt -v
```
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.3.1 (youtube-dl backend)
youtube-dl version : 2017.03.26
Python version     : 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/amit/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US
```

**Comment by ids1024** [comment]
@amitmtrn

> youtube-dl version : 2017.03.26

Update youtube-dl; that is not the latest version. An outdated youtube-dl version is usually the cause of these issues.
