### ISSUE TITLE
add catt integration

### ISSUE THREAD

**Issue by atomi** [mps-youtube/mps-youtube#607]
https://github.com/skorokithakis/catt

**Comment by ids1024** [comment]
That looks like an interesting project; although I don't own a Chromecast. Does it (partially) work to use `set player catt`?

**Comment by atomi** [comment]
cli for catt is `catt cast [url]`

so no set player won't play as is.

**Comment by ids1024** [comment]
In that case, also `set playerargs cast`. It may partially work after that.

**Comment by atomi** [comment]
Yeah `catt` doesn't stay in the foreground when playing the video. I'll open up an issue to see if we can have some way to stay in foreground at least for basic support

**Comment by ids1024** [comment]
I though that was likely to be the case. Proper support will require refactoring `player.py` to make it easier to add new player backends with different behavior.

**Comment by vn-ki** [comment]
@atomi If I make an experimental player class for catt will you be able to test it?

**Comment by atomi** [comment]
@vn-ki heck yeah.

**Comment by vn-ki** [comment]
@atomi  [Here is the branch](https://github.com/vn-ki/mps-youtube/tree/catt-support) with catt support.

If you want instructions to test it, here they are:

```
git clone https://github.com/vn-ki/mps-youtube.git
cd mps-youtube
git checkout catt-support
./mpsyt
```

Then in `mpsyt`, do `set player catt`.

The controls are:
```
> - Next
< - Previous
q - Quit(Will not stop playback since catt does not provide a method to do that)
```

I couldn't test it because I don't own a chromecast. So there will be a lot of bugs. One I can think right now is that the next song won't play automatically. This is mostly a catt disability. 

I did quick search and [castnow](https://github.com/xat/castnow) came up. It seems like it provides way more controls than catt. I think we have better chance at supporting castnow than catt. Anyway try this out.

**Comment by atomi** [comment]
@vn-ki Thanks. 

Whichever package you go with, I personally think casting is a worthwhile feature. But I don't know how many other people would find it useful. 

Anyway, getting an error with the current HEAD.

```
Traceback (most recent call last):
  File "./mpsyt", line 3, in <module>
    mps_youtube.main.main()
  File "/home/atomi/mps-youtube/mps_youtube/main.py", line 148, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/atomi/mps-youtube/mps_youtube/main.py", line 65, in matchfunction
    func(*matches)
  File "/home/atomi/mps-youtube/mps_youtube/commands/play.py", line 104, in play
    util.assign_player(config.PLAYER.get)
  File "/home/atomi/mps-youtube/mps_youtube/util.py", line 538, in assign_player
    module = import_module('.{0}'.format(player), 'mps_youtube.players')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
SystemError: Parent module 'mps_youtube.players' not loaded, cannot perform relative import
```

**Comment by vn-ki** [comment]
Did you try with mpv or mplayer? Does it work with them?

**Comment by atomi** [comment]
Yeah that error is with both mpv and catt as player.

**Comment by vn-ki** [comment]
@atomi Try with the new changes. I switched to absolute import from relative import. I was not getting this error. See if it works.

**Comment by atomi** [comment]
@vn-ki It plays the first video great. But the next video in the playlist fails

```
> Traceback (most recent call last):
  File "/home/atomi/mps-youtube/mps_youtube/main.py", line 142, in main
    userinput = next_inp or input(prompt).strip()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mpsyt", line 3, in <module>
    mps_youtube.main.main()
  File "/home/atomi/mps-youtube/mps_youtube/main.py", line 142, in main
    userinput = next_inp or input(prompt).strip()
KeyboardInterrupt
```
