### ISSUE TITLE
Crash in _launch_player caused by ctrl+c

### ISSUE THREAD

**Issue by theychx** [mps-youtube/mps-youtube#609]
Hi. When using a player other than mplayer/mpv, mpsyt crashes when the user does ctrl+c/KeyboardInterrupt:
```
Traceback (most recent call last):                                           
  File "/home/benno/.local/lib/python3.5/site-packages/mps_youtube/player.py", line 422, in _launch_player
    returncode = subprocess.call(cmd, stderr=devnull)
  File "/usr/lib/python3.5/subprocess.py", line 249, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1389, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1339, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benno/.local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/home/benno/.local/lib/python3.5/site-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/benno/.local/lib/python3.5/site-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/home/benno/.local/lib/python3.5/site-packages/mps_youtube/commands/play.py", line 85, in play
    play_range(songlist, shuffle, repeat, override)
  File "/home/benno/.local/lib/python3.5/site-packages/mps_youtube/player.py", line 41, in play_range
    returncode = _playsong(song, override=override)
  File "/home/benno/.local/lib/python3.5/site-packages/mps_youtube/player.py", line 224, in _playsong
    return _playsong(song, failcount=failcount, override=override)
  File "/home/benno/.local/lib/python3.5/site-packages/mps_youtube/player.py", line 224, in _playsong
    return _playsong(song, failcount=failcount, override=override)
  File "/home/benno/.local/lib/python3.5/site-packages/mps_youtube/player.py", line 215, in _playsong
    returncode = _launch_player(song, songdata, cmd)
  File "/home/benno/.local/lib/python3.5/site-packages/mps_youtube/player.py", line 445, in _launch_player
    if p and p.poll() is None:
UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by ids1024** [comment]
This should already be fixed in git: https://github.com/mps-youtube/mps-youtube/commit/9e0f4431bad50d5e0eeee934fcff4dbfd0893b41

**Comment by theychx** [comment]
Thanks
