### ISSUE TITLE
KeyError: 'statistics'

### ISSUE THREAD

**Issue by cesariux23** [mps-youtube/mps-youtube#616]
Hi!
I try to load some searched playlists and I get this error:
```python
Retrieving YouTube playlist

Traceback (most recent call last):
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cesariux23\AppData\Local\Programs\Python\Python35\Scripts\mpsyt.exe\__main__.py", line 9, in <module>
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\site-packages\mps_youtube\main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\site-packages\mps_youtube\main.py", line 64, in matchfunction
    func(*matches)
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\site-packages\mps_youtube\commands\play.py", line 44, in play
    return plist(g.ytpls[int(choice) - 1]['link'])
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\site-packages\mps_youtube\commands\songlist.py", line 96, in plist
    paginatesongs(pl_seg, length=len(ytpl), msg=msg, loadmsg=loadmsg)
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\site-packages\mps_youtube\commands\songlist.py", line 54, in paginatesongs
    songs = func(s, e)
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\site-packages\mps_youtube\commands\songlist.py", line 92, in pl_seg
    return [Video(i.videoid, i.title, i.length) for i in plitems[s:e]]
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\site-packages\mps_youtube\util.py", line 47, in __getitem__
    self.ilist.append(next(self.iterable))
  File "c:\users\cesariux23\appdata\local\programs\python\python35\lib\site-packages\pafy\playlist.py", line 192, in __iter__
    views=vextra['statistics'].get('viewCount',0),
KeyError: 'statistics'
```

mps-youtube and youtube-dl packages is up to date.
it's running on windows 10 and python 3

**Comment by ids1024** [comment]
This should be fixed by mps-youtube/pafy#171.
