### ISSUE TITLE
Temporary failures: album has 0 tracks

### ISSUE THREAD

**Issue by Vrihub** [mps-youtube/mps-youtube#631]
Sometimes, using the `album` command, I get the message "album XYZ has 0 tracks", just after hitting `Enter` to accept the default author suggested by mpsyt. Since this happened with some well-known albums, I tried to re-run the command after some seconds, and it obviously worked OK.

I guess that when a temporary (network?) problem with the upstream website (musicbrainz?) occurs, mpsyt displays this message by default, which can be misleading. Maybe the code can be refined? (though I'm not sure what kind of feedback can be expected by the upstream website).

**Comment by ids1024** [comment]
Could you try applying this patch (or adding those lines manually) and see what is written to `/tmp/albumsearch.log` when this happens?

```patch
diff --git a/mps_youtube/commands/album_search.py b/mps_youtube/commands/album_search.py
index fc49e47..649d25d 100644
--- a/mps_youtube/commands/album_search.py
+++ b/mps_youtube/commands/album_search.py
@@ -146,6 +146,8 @@ def _get_mb_tracks(albumid):
     url = "http://musicbrainz.org/ws/2/release/" + albumid
     query = {"inc": "recordings"}
     wdata = _do_query(url, query, err='album search error')
+    with open("/tmp/albumsearch.log", "a") as logfile:
+        logfile.write("WDATA\n=====\n" + wdata)
 
     if not wdata:
         return None
```

**Comment by Vrihub** [comment]
Thanks. Done. I'll let you know

**Comment by Vrihub** [comment]
It seems it happened again, but mpsyt crashed before displaying the message "album has 0 tracks" and before writing anything to albumsearch.log: here is what I get on the terminal:

    Traceback (most recent call last):
    File "/usr/local/bin/mpsyt", line 11, in <module>
      sys.exit(main.main())
    File "/usr/local/lib/python3.5/dist-packages/mps_youtube/main.py", line 141, in main
      if matchfunction(i.function, i.regex, userinput):
    File "/usr/local/lib/python3.5/dist-packages/mps_youtube/main.py", line 64, in matchfunction
      func(*matches)
    File "/usr/local/lib/python3.5/dist-packages/mps_youtube/commands/album_search.py", line 253, in search_album
      mb_tracks = _get_mb_tracks(album['aid'])
    File "/usr/local/lib/python3.5/dist-packages/mps_youtube/commands/album_search.py", line 153, in _get_mb_tracks
      logfile.write("WDATA\n=====\n" + wdata)
    TypeError: Can't convert 'NoneType' object to str implicitly


Right after this, I removed your patch, and ran the same exact command, and I got the "album has 0 tracks" error (so I believe the case is relevant). Then I ran it again, and it worked OK (as I described in my first post).
