### ISSUE TITLE
mpsyt crash

### ISSUE THREAD

**Issue by TG-KK** [mps-youtube/mps-youtube#663]
Since today, mpsyt is crashing whenever I'm  searching songs or even playlists for DJ KSHMR

Steps to reproduce:

1. open mpsyt
2. search for 'KSHMR' by typing `/KSHMR` or `//KSHMR`

**Comment by Ghosthree3** [comment]
Yeah I just had this happen on another search term as well.

> Traceback (most recent call last):
  File "/home/user/.local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/home/user/.local/lib/python3.6/site-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/user/.local/lib/python3.6/site-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/home/user/.local/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 212, in search
    _search(term, query, msg, failmsg)
  File "/home/user/.local/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 41, in _search
    loadmsg=loadmsg)
  File "/home/user/.local/lib/python3.6/site-packages/mps_youtube/commands/songlist.py", line 56, in paginatesongs
    songs = func[s:e]
  File "/home/user/.local/lib/python3.6/site-packages/mps_youtube/util.py", line 47, in __getitem__
    self.ilist.append(next(self.iterable))
  File "/home/user/.local/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 28, in iter_songs
    for song in get_tracks_from_json(wdata2):
  File "/home/user/.local/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 342, in get_tracks_from_json
    'id': ','.join([get_track_id_from_json(i) for i in items])}
TypeError: sequence item 9: expected str instance, dict found

**Comment by Graystripe17** [comment]
What's the command to update to the latest version?

**Comment by ritiek** [comment]
@Graystripe17 You can look up installing python packages from GitHub.
```
sudo pip3 install -U git+https://github.com/mps-youtube/mps-youtube.git
```
should do it.

**Comment by orschiro** [comment]
@ritiek tried your command but getting the following error when attempting to play a title:

```
Traceback (most recent call last):                                              
  File "/usr/local/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.7.1', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/main.py", line 143, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/main.py", line 65, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/commands/play.py", line 95, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/player.py", line 45, in play_range
    video, stream = stream_details(song, override=override, softrepeat=softrepeat)
TypeError: 'NoneType' object is not iterable
```

**Comment by ritiek** [comment]
@orschiro does it happen with every track?

**Comment by orschiro** [comment]
@ritiek yes, it does. Any ideas?

**Comment by orschiro** [comment]
@ritiek forget my previous comment. Got it to work by installing youtube-dl as follows:

    $ sudo pip3 install -U youtube-dl

Previously I had installed youtube-dl from the Ubuntu repositories which didn't work.

**Comment by ritiek** [comment]
@orschiro glad you were able to figure that out.
