### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by JPRuehmann** [mps-youtube/mps-youtube#668]
everytime I try to search for example for /Madonna mpsyt crashes with the following error.
`Searching for 'Madonna'
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4780, in main
    if matchfunction(k, v, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4680, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 2670, in search
    have_results = _search(term, query, splash)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 2460, in _search
    songs = get_tracks_from_json(wdata)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 1593, in get_tracks_from_json
    'id': ','.join([get_track_id_from_json(i) for i in items])}
TypeError: sequence item 9: expected str instance, dict found`
If I try to search for a Playlist for example //Madonna, mpsyt crashes with the following error.
`Searching playlists for Madonna
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4780, in main
    if matchfunction(k, v, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4680, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 2748, in pl_search
    qs['id'] = ','.join(id_list)
TypeError: sequence item 9: expected str instance, NoneType found`
Thanks

**Comment by ritiek** [comment]
Duplicate of #663. This is fixed on the develop branch (#664). Try installing it directly with `python3 setup.py install`.

**Comment by JPRuehmann** [comment]
This won´t work because of Update error #670

**Comment by JPRuehmann** [comment]
python3 -m pip install did the Trick
now everything except the Volume setting works.

**Comment by phoenix84pl** [comment]
I have the same problem. How to fix that?
