### ISSUE TITLE
Can't seek to next song or save playlist. Charmap

### ISSUE THREAD

**Issue by Recchan** [mps-youtube/mps-youtube#693]
On the latest developer version, I'm getting the same error regardless of what playlist I load. Seeking or saving a playlist shows this error.
"Problem playing last item: 'charmap' codec can't encode character '\u2012' in position 17: character maps to <undefined>"
Everything worked for the commits made on August 28.

**Comment by ritiek** [comment]
Are you on windows? If so, try again after updating to Python 3.6. It fixes some common unicode problems.

**Comment by WolfeCub** [comment]
I'm on windows with python 3.6.5 and I'm getting this issue.

**Comment by WolfeCub** [comment]
Upon further investigation I've tracked it down to this line:

**Comment by WolfeCub** [comment]
I've noticed another similar issue here:

https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube/playlists.py#L66

it also requires an `encoding='utf8'` in order to work.

**Comment by Razesdark** [comment]
I think it would be better if we converted all the files to utf-8.

**Comment by airstrike** [comment]
Worth noting that changing the calls to `open()` as suggested above can potentially prevent the app from loading if your existing history file already has incompatible characters from whatever default encoding you had going on originally.

    Traceback (most recent call last):
      File "c:\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\python\python36-32\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Python\Python36-32\Scripts\mpsyt.exe\__main__.py", line 9, in <module>
      File "c:\python\python36-32\lib\site-packages\mps_youtube\main.py", line 121, in main
        history.load()
      File "c:\python\python36-32\lib\site-packages\mps_youtube\history.py", line 24, in load
        g.userhist['history'] = read_m3u(g.HISTFILE)
      File "c:\python\python36-32\lib\site-packages\mps_youtube\playlists.py", line 67, in read_m3u
        if plf.readline().startswith('#EXTM3U'):
      File "c:\python\python36-32\lib\codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 135: invalid start byte`

On Windows, the history file lives under `%APPDATA%\mps-youtube\play_history.m3u` – just delete that and you're good to go

**Comment by AyoungDukie** [comment]
I came across this issue when trying to save a playlist with a song/video that has a unicode character in the name, so just note this can be fixed in a similar way on the save command:

https://github.com/mps-youtube/mps-youtube/blob/9000a1a79ac9d10e06dd4fff81e24e4efeded563/mps_youtube/playlists.py#L13

Modifying to be: `with open(os.path.join(g.PLFOLDER, pl+'.m3u'), 'w', encoding='utf8') as plf:` instead.

**Comment by Mansouri147** [comment]
I got the same error message but when first running mpsyt in terminal it directly throws an Error
the fix was in this file `C:\Users\user\anaconda3\Lib\site-packages\pyreadline\lineeditor\history.py`
I changed this line 
`            for line in open(filename, 'r'):`
to this
`             for line in open(filename, 'r', encoding='utf8'):`
