### ISSUE TITLE
Crashes on search

### ISSUE THREAD

**Issue by moosingin3space** [mps-youtube/mps-youtube#703]
Today, I noted a new `youtube-dl` version and upgraded it. When I went to search in `mpsyt`, it crashed with the following error:
```
Traceback (most recent call last):
  File "/home/[REDACTED]/.local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/home/[REDACTED]/.local/lib/python3.6/site-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/[REDACTED]/.local/lib/python3.6/site-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/home/[REDACTED]/.local/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 212, in search
    _search(term, query, msg, failmsg)
  File "/home/[REDACTED]/.local/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 41, in _search
    loadmsg=loadmsg)
  File "/home/[REDACTED]/.local/lib/python3.6/site-packages/mps_youtube/commands/songlist.py", line 56, in paginatesongs
    songs = func[s:e]
  File "/home/[REDACTED]/.local/lib/python3.6/site-packages/mps_youtube/util.py", line 47, in __getitem__
    self.ilist.append(next(self.iterable))
  File "/home/[REDACTED]/.local/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 28, in iter_songs
    for song in get_tracks_from_json(wdata2):
  File "/home/[REDACTED]/.local/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 342, in get_tracks_from_json
    'id': ','.join([get_track_id_from_json(i) for i in items])}
TypeError: sequence item 9: expected str instance, dict found
```
Occured on Fedora 26 with `youtube-dl` version `2017.10.15.1`.

**Comment by TheCatWizard** [comment]
I'm getting the same issue. I think it might have something to do with what search results are returned, rather than what the search query is.

**Comment by ritiek** [comment]
Check out #663.
