### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by justijndepover** [mps-youtube/mps-youtube#708]
When I try to open `mpsyt` i get the following error:

```
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/bin/mpv
  Reason: image not found
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/init.py", line 67, in init
    load_player_info(config.PLAYER.get)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/util.py", line 388, in load_player_info
    g.mpv_version = _get_mpv_version(player)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/util.py", line 406, in _get_mpv_version
    o = subprocess.check_output([exename, "--version"]).decode()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mpv', '--version']' died with <Signals.SIGABRT: 6>.
```

I think it started after I did `brew update`

My info:
OS: macOS High Sierra 10.13
mpsyt version      : 0.2.7.1
notes           : released 6 July 2016
pafy version       : 0.5.3.1 (youtube-dl backend)
youtube-dl version : 2017.06.05
Python version     : 3.6.1 (default, Jun  1 2017, 13:54:58)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-17.0.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/justijndepover/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh

**Comment by justijndepover** [comment]
Ok, i've managed to solve it on my own. Followed steps [here](https://stackoverflow.com/a/45695529/3182055)

The issue is that Homebrew's jpeg formula has been upgraded to v9 but the existing "bottled" PHP formula is still built and linked against the previous version, v8, which is no longer exists on my system.

essentially the only thing that I needed to do was `brew switch jpeg 8d`

**Comment by justijndepover** [comment]
Previous solutions solved the issue but wasn't the best of solutions.
A far better solution is to reinstall mpv.

```
brew reinstall mpv
```
