### ISSUE TITLE
Not working on Xubuntu 18.04: pip3 install dbus-python pygobject

### ISSUE THREAD

**Issue by orschiro** [mps-youtube/mps-youtube#727]
Just tried to run the command `pip3 install dbus-python pygobject` on Xubuntu 18.04 but it failed with the following error. Can anyone help me?

```
orschiro@x230:~$ sudo pip3 install dbus-python pygobject
[sudo] password for orschiro: 
The directory '/home/orschiro/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/orschiro/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting dbus-python
  Downloading dbus-python-1.2.4.tar.gz (612kB)
    100% |████████████████████████████████| 614kB 1.5MB/s 
Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages
Installing collected packages: dbus-python
  Running setup.py install for dbus-python ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4j7alcwc/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8y4k5tna-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    creating /tmp/pip-build-4j7alcwc/dbus-python/build
    creating /tmp/pip-build-4j7alcwc/dbus-python/build/temp.linux-x86_64-3.6
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether UID '0' is supported by ustar format... yes
    checking whether GID '0' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking for native Windows host... no
    checking how to print strings... printf
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for inline... inline
    checking whether /usr/bin/python3 version is >= 2.6... yes
    checking for /usr/bin/python3 version... 3.6
    checking for /usr/bin/python3 platform... linux
    checking for /usr/bin/python3 script directory... ${prefix}/lib/python3.6/site-packages
    checking for /usr/bin/python3 extension module directory... ${exec_prefix}/lib/python3.6/site-packages
    configure: Using $PYTHON-config: /usr/bin/python3-config
    checking for Python headers using /usr/bin/python3-config --includes... -I/usr/include/python3.6m -I/usr/include/python3.6m
    checking whether those headers are sufficient... yes
    checking for Python library linker flags using /usr/bin/python3-config... -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/usr/lib -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    checking for git... ${SHELL} /tmp/pip-build-4j7alcwc/dbus-python/build-aux/missing git
    checking whether you want to build HTML docs... if possible
    checking whether you want to build API docs... if possible
    checking python3 module: docutils... no
    checking for dbus-run-session... /usr/bin/dbus-run-session
    checking whether  understands --generator... no
    checking whether  understands --date... no
    checking whether  understands --time... no
    checking whether  understands --exit-status=2... no
    checking whether  understands --no-raw... no
    checking whether  understands --no-file-insertion... no
    checking whether  understands --cloak-email-addresses... no
    checking whether  understands --input-encoding=UTF-8... no
    checking for pkg-config... no
    checking for DBUS... no
    configure: error: in `/tmp/pip-build-4j7alcwc/dbus-python/build/temp.linux-x86_64-3.6':
    configure: error: The pkg-config script could not be found or is too old.  Make sure it
    is in your PATH or set the PKG_CONFIG environment variable to the full
    path to pkg-config.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    
    To get pkg-config, see <http://pkg-config.freedesktop.org/>.
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4j7alcwc/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-4j7alcwc/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-4j7alcwc/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-build-4j7alcwc/dbus-python/build/temp.linux-x86_64-3.6/prefix']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4j7alcwc/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8y4k5tna-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-4j7alcwc/dbus-python/
```

**Comment by orschiro** [comment]
This is potentially related: https://xfce.space/en/2017/11/multimediatasten-und-mpris2/#comment-27

**Comment by hrnr** [comment]
Hi,

i don't think it is related. AFAIK mps-youtube is not using pulse audio directly. MPRIS2 is implemented with just dbus bindings.

I think you are missing some dbus libraries (libdbus). Don't install via pip, simple install dbus-python from your distribution e.g.:

```
sudo apt install python3-dbus
```

this will get you all dependencies.

**Comment by orschiro** [comment]
Thank you!

I have this packaged already installed but using the media keys of my laptop on Xubuntu 18.04 doesn't have any effect. Seem to be missing something else...

```
orschiro@x230:~$ sudo apt install python3-dbus
[sudo] password for orschiro: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-dbus is already the newest version (1.2.4-1build3).
The following package was automatically installed and is no longer required:
  python-gi
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by hrnr** [comment]
ok. Lets debug that.

At first lets verify if mps-youtube MPRIS interface is running. Run:

```
dbus-send --session           \
  --dest=org.freedesktop.DBus \
  --type=method_call          \
  --print-reply=literal       \
  /org/freedesktop/DBus       \
  org.freedesktop.DBus.ListNames |
  tr ' ' '\n' |
  grep 'org.mpris.MediaPlayer2'
```

You need package `dbus` for `dbus-send`.

If it prints something like:

```
org.mpris.MediaPlayer2.mps-youtube.instance9191
```

All is fine and you have probably problem with your XFCE. If it does not print anything, we can debug further.

**Comment by orschiro** [comment]
```
orschiro@x230:~$ dbus-send --session           \
>   --dest=org.freedesktop.DBus \
>   --type=method_call          \
>   --print-reply=literal       \
>   /org/freedesktop/DBus       \
>   org.freedesktop.DBus.ListNames |
>   tr ' ' '\n' |
>   grep 'org.mpris.MediaPlayer2'
org.mpris.MediaPlayer2.mps-youtube.instance7141
```
Thank you for your help!

Hence a problem on my Xubuntu 18.04 installation. 

I guess it's best to close this issue. Probably related to the fact that 18.04 is unstable alpha. 

I need to test on 17.10.

**Comment by hrnr** [comment]
Yes, the problem probably is that media key presses are not translated to MPRIS2 commands. I'm not sure which component of XFCE is responsible for this, or if they even support MPRIS2 by default on media keys.

You can still use a script I created https://gist.github.com/hrnr/43d926875577f6c3fd70 to control mps-youtube (or actually all players that support MPRIS2). You can also bind your media keys to this script and be happy regardless of XFCE support. (Yes, it is that easy. You don't really need pulseaudio plugin to have working MPRIS2.)

**Comment by orschiro** [comment]
Thank you for all your help, @hrnr!

I suspect something currently broken on Ubuntu 18.04. 

I tried the Ubuntu 18.04 Unity 7 Remix and the same problem there. 

Will close this for now.
