### ISSUE TITLE
Crash when searching for 'mind field'

### ISSUE THREAD

**Issue by Zarthus** [mps-youtube/mps-youtube#731]
```
Searching for 'mind field'                                                                                  
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/lib/python3.6/site-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.6/site-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 212, in search
    _search(term, query, msg, failmsg)
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 41, in _search
    loadmsg=loadmsg)
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/songlist.py", line 56, in paginatesongs
    songs = func[s:e]
  File "/usr/lib/python3.6/site-packages/mps_youtube/util.py", line 47, in __getitem__
    self.ilist.append(next(self.iterable))
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 28, in iter_songs
    for song in get_tracks_from_json(wdata2):
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 342, in get_tracks_from_json
    'id': ','.join([get_track_id_from_json(i) for i in items])}
TypeError: sequence item 0: expected str instance, dict found
```

```
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.3.1 (youtube-dl backend)
youtube-dl version : 2017.11.15
Python version     : 3.6.3 (default, Oct  9 2017, 12:11:29) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.13.16-200.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/jahrens/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh
env:LANG           : en_US.UTF-8
```
```
  order             : relevance
  user_order        : 
  max_res           : 2160p
  player            : mplayer
  playerargs        : 
  encoder           : 0 [None]
  notifier          : 
  checkupdate       : True
  show_mplayer_keys : True
  fullscreen        : False
  show_status       : True
  columns           : views date user
  ddir              : /home/jahrens/Downloads/mps
  overwrite         : True
  show_video        : False
  search_music      : False
  window_pos        : 
  window_size       : 
  download_command  : 
  audio_format      : auto
```

**Comment by ritiek** [comment]
Hi there! check out #663.

**Comment by Zarthus** [comment]
Cool!  I will admit I hadn't searched beforehand and just created the ticket in a rush, but I will close this as duplicate and check later if updating to git:master will resolve the issue here too.
