### ISSUE TITLE
KeyError: 'dashmpd'

### ISSUE THREAD

**Issue by aarraall** [mps-youtube/mps-youtube#771]
## Issue / Suggestion

`> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3497, in preload
    stream = get_streams(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
`
I installed pafy and youtube-dl by using pip3 but, it still does not work

**Comment by ids1024** [comment]
> mpsyt version : 0.2.5

That version is from 2015; try updating.
