### ISSUE TITLE
mps-youtube stop

### ISSUE THREAD

**Issue by chivmalev** [mps-youtube/mps-youtube#800]
Hello
mps-youtube  stops and does not continue with the next song

~ » mpsyt --version                                               ivan@linux-PC
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.02.26
Python version     : 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
Processor          : i686
Machine type       : i686
Architecture       : 32bit, ELF
Platform           : Linux-4.13.0-36-generic-i686-with-Ubuntu-16.04-xenial
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/ivan/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /usr/bin/zsh
env:LANG           : es_AR.UTF-8
env:LANGUAGE       : es_AR:es
![2018-03-02-214927_1024x600_scrot](https://user-images.githubusercontent.com/36960420/36928437-b8d5a690-1e64-11e8-84b8-9afabace2c95.png)

**Comment by DnD-Von** [comment]
Well. I guess the video is not available in your country. Try using a VPN, or listen to another song

**Comment by VonKavalier** [comment]
Well. I guess the video is not available in your country. Try using a VPN, or listen to another song

**Comment by ritiek** [comment]
Similar thing happens if a video is not available at all. For example, the 2nd song is not available any more in this test playlist and mpsyt crashes when her turn comes.
```
#EXTM3U

#EXTINF:130,Made in Abyss OST: 2. The First Layer
https://www.youtube.com/watch?v=NSmukdqyvjU
#EXTINF:110,Made in Abyss Soundtrack: Rafters
https://www.youtube.com/watch?v=HEKpR1HwJvw
#EXTINF:197,Made in Abyss OST - Underground River Full (ft.Raj Ramayya) Episode 1 Opening Theme
https://www.youtube.com/watch?v=Eck3qf4FDf4
```
<details>

```
   Title                                                                                                                                                            Time
  Made in Abyss OST: 2. The First Layer                                                                                                                           02:10
> Made in Abyss Soundtrack: Rafters                                                                                                                               01:50
  Made in Abyss OST - Underground River Full (ft.Raj Ramayya) Episode 1 Opening Theme                                                                             03:17

    [←] seek [→]       [9] volume [0]      [CTRL-C] return
    [↓] SEEK [↑]       [space] pause       [>] next/prev [<]        2 of 3

    Made in Abyss Soundtrack: Rafters [01:50]
ERROR: This video is unavailable.
ERROR: This video is unavailable.
ERROR: This video is unavailable.
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1875, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 40, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 590, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/player.py", line 316, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/util.py", line 206, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/local/lib/python3.6/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 43, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1875, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 40, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 590, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/player.py", line 316, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/util.py", line 206, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/local/lib/python3.6/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 43, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1875, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 40, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 590, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/player.py", line 316, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/util.py", line 206, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/local/lib/python3.6/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 43, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube', 'console_scripts', 'mpsyt')()
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/main.py", line 152, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/main.py", line 69, in matchfunction
    func(*matches)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/commands/play.py", line 123, in play_all
    play(options, "1-" + str(len(g.model)))
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/commands/play.py", line 103, in play
    g.PLAYER_OBJ.play(songlist, shuffle, repeat, override)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/player.py", line 74, in play
    softrepeat=self.softrepeat)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/player.py", line 328, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/player.py", line 328, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/player.py", line 328, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/home/ritiek/Downloads/mps-youtube/mps_youtube/player.py", line 343, in stream_details
    cached = g.streams[song.ytid]
KeyError: 'HEKpR1HwJvw'
```

</details>
