### ISSUE TITLE
AttributeError: 'mpv' object has no attribute 'mpv_usesock'  (Windows)

### ISSUE THREAD

**Issue by elig0n** [mps-youtube/mps-youtube#825]
When trying to play a selection using mpsyt 0.2.8 (git) on windows and latest mpv 

    Traceback (most recent call last):
      File "mpsyt", line 3, in <module>
        mps_youtube.main.main()
      File "D:\GitHub\mps-youtube\mps_youtube\main.py", line 152, in main
        if matchfunction(i.function, i.regex, userinput):
      File "D:\GitHub\mps-youtube\mps_youtube\main.py", line 69, in matchfunction
        func(*matches)
      File "D:\GitHub\mps-youtube\mps_youtube\commands\play.py", line 103, in play
        g.PLAYER_OBJ.play(songlist, shuffle, repeat, override)
      File "D:\GitHub\mps-youtube\mps_youtube\player.py", line 71, in play
        self._playsong()
      File "D:\GitHub\mps-youtube\mps_youtube\player.py", line 133, in _playsong
        self._launch_player()
      File "D:\GitHub\mps-youtube\mps_youtube\player.py", line 277, in _launch_player
        cmd = self._generate_real_playerargs()
      File "D:\GitHub\mps-youtube\mps_youtube\players\mpv.py", line 90, in _generate_real_playerargs
        if self.mpv_usesock:
    AttributeError: 'mpv' object has no attribute 'mpv_usesock'

**Comment by novia713** [comment]
me having this problem :-/

**Comment by tigerjack** [comment]
Same here

**Comment by GokulNC** [comment]
@panasenco The still persists even in the latest `develop` branch.

I had to go to `C:\Program Files\Python38\Lib\site-packages\mps_youtube\players` and manually add a default `self.mpv_usesock = ""` in the `mpv` class.

Please fix this, such that even if `mswin` is True, set the above string as empty
