### ISSUE TITLE
Application crashes when video is unavailable

### ISSUE THREAD

**Issue by nour-s** [mps-youtube/mps-youtube#847]
When the video is unavailable, the program crashes.

## Issue / Suggestion
I get the following error:

ERROR: "Aura - If ..." The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1990, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 590, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/local/lib/python3.6/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1990, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 590, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/local/lib/python3.6/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1990, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 590, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/local/lib/python3.6/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/main.py", line 148, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/main.py", line 65, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/commands/play.py", line 100, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 49, in play_range
    video, stream = stream_details(song, override=override, softrepeat=softrepeat)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 171, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 171, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 171, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 186, in stream_details
    cached = g.streams[song.ytid]
KeyError: '5FvJ_tir0N0'

## Your Environment

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.05.26
Python version     : 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Darwin-17.6.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/nour.sabouny/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh

OS: MacOs High Sierra

**Comment by Razesdark** [comment]
I'm unable to replicate this. What commands did you use that led you to these errors?

**Comment by nour-s** [comment]
I opened a saved playlist named fav:
open fav
The list has a video which owner's account is suspended. When the player reached that video it crashed as you can see from the dump in the post. 

Here is the play list if you want, you can save it as m3u file and play it:

> 
#EXTM3U

#EXTINF:382,Christos Fourkis - Secret Love [Original Mix] | VideoClip ᴴᴰ by yanniszita | Hotworx Records
https://www.youtube.com/watch?v=ZHb1OvnuZzg
#EXTINF:350,Minus Blue feat Emma Saville - Be As One ( Klangstein Mix)
https://www.youtube.com/watch?v=Czd9eOA919o
#EXTINF:448,Sahalé - Shérazade
https://www.youtube.com/watch?v=pAkljYCPzVc
#EXTINF:434,Fading Soul - Ωrion (Original Mix)
https://www.youtube.com/watch?v=Zi1DyyHpA5w
#EXTINF:512,Boral Kibil & Feri: Never Give Up (Original Mix)
https://www.youtube.com/watch?v=6L9D0_pulKE
#EXTINF:562,Aura - If You
https://www.youtube.com/watch?v=5FvJ_tir0N0
#EXTINF:255,Enigma - MMX The Social Song - With Lyrics
https://www.youtube.com/watch?v=C932Ukl-YDk
#EXTINF:6625,Mongolca Amethystium (Best of the Best)
https://www.youtube.com/watch?v=M1TtAXcJVWM
#EXTINF:6170,A Tribute to Amethystium [High Quality]
https://www.youtube.com/watch?v=U9jAIXJW_IA

>

**Comment by Razesdark** [comment]
Thanks, I will look into it

**Comment by Razesdark** [comment]
I'm gonna leave the PR mentioned here up for a few days to give other contributors the time to chime in. If no objects are raised, I'll be merging that as a fix to this issue.

**Comment by Laxa** [comment]
Just wanna mention that this bug also happens when a video is unavailable in some country.
Also a weird bug, I have some songs that pop an error message but are correctly loaded on the second try. (max retries is 3)

**Comment by evolutionxbox** [comment]
I also have this issue, but I'm pretty sure I screwed up my python installation.

**Comment by haroonjameel** [comment]
same issue here
"youtube_dl.utils.DownloadError: ERROR: This video is unavailable."

`ERROR: This video is unavailable.

Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
ie_result = ie.extract(url)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
ie_result = self._real_extract(url)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1982, in _real_extract
raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "./youtube-dl-server.py", line 60, in dl_worker
download(url, options)
File "./youtube-dl-server.py", line 106, in download
ydl.download([url])
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2006, in download
url, force_generic_extractor=self.params.get('force_generic_extractor', False))
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 805, in extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1004, in process_ie_result
extra_info=extra)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 866, in process_ie_result
extra_info=extra_info)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 817, in extract_info
self.report_error(compat_str(e), e.format_traceback())
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 622, in report_error
self.trouble(error_message, tb)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 592, in trouble
raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is unavailable.`
