### ISSUE TITLE
Raspberry pi 3b+ and SyntaxError: invalid syntax with AIY

### ISSUE THREAD

**Issue by Rheyd** [mps-youtube/mps-youtube#851]
i'm using and AIY kit (last version of the OS) and install this, because it's awesome following this instructions
https://learn.adafruit.com/piglass-wearable-raspberry-pi-computer/youtube-video-streaming
but when i tried to test it out this happens

pi@raspberrypi:~ $ mpsyt
mpv
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube-0.2.8-py3.5.egg/mps_youtube/__init__.py", line 8, in <module>
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube-0.2.8-py3.5.egg/mps_youtube/init.py", line 47, in init
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube-0.2.8-py3.5.egg/mps_youtube/config.py", line 154, in set
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube-0.2.8-py3.5.egg/mps_youtube/config.py", line 269, in check_player
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube-0.2.8-py3.5.egg/mps_youtube/util.py", line 546, in assign_player
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube-0.2.8-py3.5.egg/mps_youtube/players/mpv.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube-0.2.8-py3.5.egg/mps_youtube/player.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube-0.2.8-py3.5.egg/mps_youtube/commands/__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube-0.2.8-py3.5.egg/mps_youtube/commands/config.py", line 19
    s = f"  %s%-{longest_key}s%s : %-{longest_val+1}s"
                                                     ^
SyntaxError: invalid syntax

**Comment by vn-ki** [comment]
Looks like there's f-strings in config.py. Even though it's one of my favorite feature in Python, it's only supported by python 3.6+. 

So you either have to update your python to 3.6 or change mpsyt code to use `.format` instead. 

If you do the second, don't forget to open a PR.

**Comment by ids1024** [comment]
Ah yes, as much as I like `f"` strings, we probably shouldn't use features requiring python 3.6. I'm not sure how old of a version we should support, and how to test that it is correct...

**Comment by hrnr** [comment]
I agree. I think targeting current Debian stable should be conservative enough for us, while not being painfully old. Users of older distros usually have some way to use backported python.

Currently (https://tracker.debian.org/pkg/python3-defaults) that means Python 3.5.

**Comment by Insane88** [comment]
I'm having the same problem with raspberry pi 3.. same python 3.5 stable installed
