### ISSUE TITLE
HTTP Error 403: Forbidden: category denied

### ISSUE THREAD

**Issue by drzacek** [mps-youtube/mps-youtube#864]
When trying to play anything in mpsyt, I get this error. 

Tried reinstalling with pip3, nothing helps.

I'm on debian stretch 64bit

`$ mpsyt --debug
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.07.04
Python version     : 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/jack/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : pl_PL.UTF-8
--

Enter /search-term to search or [h]elp                                                                            
> /wildstylez encore
--

Searching for 'wildstylez encore'                                                                        
--
[List of records found]

Search results for wildstylez encore                                                      [1/15>
> 1
--

--esUnDTrXsU; m4a 128k; 3 Mb                                                                                      

Traceback (most recent call last):
  File "/home/jack/.local/lib/python3.5/site-packages/mps_youtube/main.py", line 65, in matchfunction
    func(*matches)
  File "/home/jack/.local/lib/python3.5/site-packages/mps_youtube/commands/play.py", line 100, in play
    play_range(songlist, shuffle, repeat, override)
  File "/home/jack/.local/lib/python3.5/site-packages/mps_youtube/player.py", line 50, in play_range
    returncode = _playsong(song, stream, video, override=override, softrepeat=softrepeat)
  File "/home/jack/.local/lib/python3.5/site-packages/mps_youtube/player.py", line 240, in _playsong
    returncode = _launch_player(song, songdata, cmd)
  File "/home/jack/.local/lib/python3.5/site-packages/mps_youtube/player.py", line 392, in _launch_player
    metadata = util._get_metadata(song.title)
  File "/home/jack/.local/lib/python3.5/site-packages/mps_youtube/util.py", line 498, in _get_metadata
    metadata = _get_metadata_from_lastfm(t[0], t[1])
  File "/home/jack/.local/lib/python3.5/site-packages/mps_youtube/util.py", line 513, in _get_metadata_from_lastfm
    resp = urllib.request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden: category denied

Problem playing last item: HTTP Error 403: Forbidden: category denied                 [1/15>
> `

**Comment by Razesdark** [comment]
Hmm, interesting error. From the looks of it the last.fm api is returning you some error that involves `category denied` which is somewhat of a bizarre message and no message like that is documented in the last.fm api as far as I can see anyways.

From the looks of it, you are running the standard 0.28.0 tagged release from one of the repositories. There are several bugfixes and what not in the current `develop` branch version here on github.

Regardless of the errors, lastfm scrobbling should not be able to halt playback even when it breaks so I will be opening a PR with a fix asap

**Comment by vn-ki** [comment]
Closed in #866
