### ISSUE TITLE
Youtube-dl error

### ISSUE THREAD

**Issue by VonKavalier** [mps-youtube/mps-youtube#888]
## Issue / Suggestion

I get a youtube-dl error when playing music

## Your Environment

- Last version of mps-youtube and youtube-dl
- OSX
- iTerm2
- ohmyzsh

## Logs

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/mps-youtube/0.2.8_2/libexec/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/Cellar/mps-youtube/0.2.8_2/libexec/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/Cellar/mps-youtube/0.2.8_2/libexec/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/Cellar/mps-youtube/0.2.8_2/libexec/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Rom1deTroyes** [comment]
> - Last version of mps-youtube and youtube-dl

Last is not least :-)
If your "last version" of youtube-dl comes from a source other than
yt-dl.org it may be outdated...

> youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS
> player signature function name; please report this issue on
> https://yt-dl.org/bug . Make sure you are using the latest version;
> see  https://yt-dl.org/update  on how to update. Be sure to call
> youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl --version
2018.09.10

++
   Romain
-- 
La nouvelle preuve montre (ou crée) une nouvelle connexion.
	-+- Ludwig von Wittgenstein, Remarques sur les fondements des
	    mathématiques -+-

**Comment by VonKavalier** [comment]
@Rom1deTroyes :
You were right, I was updating stuff with pip while I was running the brew installation x) Thanks !
