### ISSUE TITLE
Started getting ValueError: Need 11 character video id or the URL of the video. Got //subscribe yb 

### ISSUE THREAD

**Issue by therimalaya** [mps-youtube/mps-youtube#894]
## My Issue

I started getting following error when I start `mpsyt` in my mac. I removed both `youtube-dl` and `mps-youtube`. I tried to reinstall from both `brew` and `pip` but neither worked. The error is as follows,

```
Enter /search-term to search or [h]elp
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python3.7/site-packages/mps_youtube/main.py", line 121, in main
    history.load()
  File "/usr/local/lib/python3.7/site-packages/mps_youtube/history.py", line 24, in load
    g.userhist['history'] = read_m3u(g.HISTFILE)
  File "/usr/local/lib/python3.7/site-packages/mps_youtube/playlists.py", line 73, in read_m3u
    ytid = extract_video_id(line).strip()
  File "/usr/local/lib/python3.7/site-packages/pafy/backend_shared.py", line 51, in extract_video_id
    raise ValueError(err % url)
ValueError: Need 11 character video id or the URL of the video. Got //subscribe yb
```

## My Environment

I am using Mac with macOS Mohave (v 10.14). The output from `mpsyt --version` is as follows:

```
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.10.05
Python version     : 3.7.0 (default, Oct  2 2018, 09:18:58)
[Clang 10.0.0 (clang-1000.11.45.2)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-18.0.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/myusername/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh
env:LANG           : en_US.UTF-8
```

I have no idea what is happening.

**Comment by therimalaya** [comment]
I tried to install 0.2.7.1 version and it is working perfectly fine.

**Comment by klopsi** [comment]
```
mpsyt playurl https://youtu.be/xsUIyltGD9Y
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/main.py", line 121, in main
    history.load()
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/history.py", line 24, in load
    g.userhist['history'] = read_m3u(g.HISTFILE)
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/playlists.py", line 73, in read_m3u
    ytid = extract_video_id(line).strip()
  File "/usr/local/lib/python3.6/dist-packages/pafy/backend_shared.py", line 51, in extract_video_id
    raise ValueError(err % url)
ValueError: Need 11 character video id or the URL of the video. Got //(
```
mpsyt version      : 0.2.8
pafy version        : 0.5.4
youtube-dl ver.    : 2018.10.05

Could it be that mpsyt got some bad url in a cache that it is trying to load upon startup? (to restore state?)

**Comment by JingYenLoh** [comment]
I had the same issue and deleting the `input_history` file helped. My input history was in `~/.config/mps-youtube`, looking through the code in `paths.py` it seems it may be in different locations depending on the operating system.

**Comment by therimalaya** [comment]
Thank you @JingYenLoh for the solution. It did not work when I removed only `input_history` but when I removed everything in the `~/.config/mps-youtube/*`, it worked.

> I had the same issue and deleting the `input_history` file helped. My input history was in `~/.config/mps-youtube`, looking through the code in `paths.py` it seems it may be in different locations depending on the operating system.
