### ISSUE TITLE
mpsyt not starting on Manjaro

### ISSUE THREAD

**Issue by hazeshrapnel** [mps-youtube/mps-youtube#947]
When running mpsyt 0.2.8 in Manjaro 18.0.2 xfce  all I get is:

Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/.local/lib/python3.7/site-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/home/user/.local/lib/python3.7/site-packages/mps_youtube/init.py", line 58, in init
    cache.load()
  File "/home/user/.local/lib/python3.7/site-packages/mps_youtube/cache.py", line 21, in load
    cached = pickle.load(cf)
_pickle.UpicklingError: pickle data was truncated

A bit new to Linux. Tried looking around for a solution. I am running python3 as far as I understand, also tried uninstalling and reinstalling.

My environment:

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.01.30.1
Python version     : 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.20.3-1-MANJARO-x86_64-with-arch-Manjaro-Linux
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/user/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.utf8

**Comment by hrnr** [comment]
try deleting your config dir: `/home/user/.config/mps-youtube`

**Comment by hazeshrapnel** [comment]
> try deleting your config dir: `/home/user/.config/mps-youtube`

Thank you! :)
