### ISSUE TITLE
Long error message cannot start mpsyt

### ISSUE THREAD

**Issue by DavidBot013** [mps-youtube/mps-youtube#970]
Whenever i try to start mpsyt a long error message appears in the console, then nothing.
## Issue / Suggestion

**Here is the full ouput**
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pafy/util.py", line 34, in call_gdata
    data = g.opener.open(url).read().decode('utf-8')
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/mps_youtube/__init__.py", line 8, in <module>
init.init()
  File "/usr/lib/python3.7/site-packages/mps_youtube/init.py", line 58, in init
    cache.load()
  File "/usr/lib/python3.7/site-packages/mps_youtube/cache.py", line 34, in load
    pafy.load_cache(cached['pafy'])
  File "/usr/lib/python3.7/site-packages/pafy/pafy.py", line 184, in load_cache
    set_categories(newcache.get('categories', {}))
  File "/usr/lib/python3.7/site-packages/pafy/pafy.py", line 171, in set_categories
    catinfo = call_gdata('videoCategories', query)
  File "/usr/lib/python3.7/site-packages/pafy/util.py", line 42, in call_gdata
    raise GdataError(errmsg)
pafy.util.GdataError: Youtube Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.

## Your Environment

I'm on version 0.2.8, downloaded form the arch repos. Currently on kernel 5.0.6 and iḿ just using vlc with args -I rc to play in console

**Comment by gmircea** [comment]
I also got a similar message when searching for something:
```
Error fetching data. Possible network issue.
Youtube Error 403: Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=422897895433
```

**Comment by kudo-shinichi** [comment]
Happened with for the first time today. Here is how I got it working:

1. Edit the config.py file placed in /usr/lib/python3.7/site-packages/mps_youtube/.
2. Find the line ConfigItem("api_key", "AIza.......".
3. Change the API key, either use the one provided by jdsampayo or generate one for yourself from google developer using this help page, ([https://www.slickremix.com/docs/get-api-key-for-youtube/#])

It began to work after I followed the above steps.

**Comment by steve-chavez** [comment]
It's possible to configure the api key through `set api_key <xx>` in mpsyt. But if the default key has the quota exceeded one cannot enter `mpsyt` because the issuer error is shown.

Could a plain text config file be offered to set the config values? Right now the config file is a binary one.

**Comment by ev-agelos** [comment]
@steve-chavez from `mpsyt --help` -> `All mpsyt commands can be entered from the command line`
I also created one and set it via command line and worked.

**Comment by mihaigalos** [comment]
> @steve-chavez from `mpsyt --help` -> `All mpsyt commands can be entered from the command line`
> I also created one and set it via command line and worked.

Why do you write a semi-complete post?! If you truly want to help, please provide your invocation.

**Comment by ev-agelos** [comment]
@mihaigalos I am not sure if I did not communicate it correctly but I showed above that the same commands you run inside the cli of mpsyt you can run them also outside (as per `mpsyt --help`) so:
`$ mpsyt set api_key <YOUR_API_KEY>`

**Comment by DavidBot013** [comment]
@ev-agelos Doing that solved the issue, although i had to restart mpsyt as someone said in #551
