### ISSUE TITLE
Throws token errors when trying to play anything.

### ISSUE THREAD

**Issue by slole** [mps-youtube/mps-youtube#985]
When I try to play anything it throws me this error:
```
ERROR: V1Pl8CzNzCw: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
and then this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1689, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: V1Pl8CzNzCw: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jan/.local/lib/python3.5/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 817, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 622, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 592, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: V1Pl8CzNzCw: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
I thought it was a youtube-dl error, however, I tried several different versions and nothing worked. I the tried dowloading a video with youtube-dl by itself and it worked, but mps-youtube still doesn't work

## Environment

```mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.03.01
Python version     : 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
Processor          : 
Machine type       : i686
Architecture       : 32bit, 
Platform           : Linux-4.9.0-9-686-pae-i686-with-debian-9.9
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/jan/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US:en
```

```
youtube-dl --version
2019.05.20
```

**Comment by azisyus** [comment]
@slole Did you try to reinstall or update your youtube-dl? also this issue is probably dupe of #981, as you can see the output of <code>youtube-dl --version</code> is <code>2019.05.20</code> but your <code>mpsyt -v</code> says its <code>youtube-dl version : 2019.03.01</code> and thats probably why mpsyt gives the error output you specified.

**Comment by slole** [comment]
Ooooooh, I didn't catch that. Thanks.
